// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/comic.dart';
import 'api/history.dart';
import 'api/home.dart';
import 'api/init.dart';
import 'api/reader.dart';
import 'api/series.dart';
import 'api/sync.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiComicInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 775622949;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'hentai_flutter',
        ioDirectory: '../core/crates/flutter/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  void crateApiSyncCancelSyncFrb({required SyncHandleDto handle});

  int crateApiHistoryClearAllReadingFrb();

  void crateApiReaderClearReaderSessionsFrb();

  void crateApiReaderCloseReaderFrb({required String comicId});

  String crateApiComicComicIdFromPathFrb({required String rawPath});

  PlatformInt64 crateApiComicCountAllComicsFrb();

  SyncHandleDto crateApiSyncCreateSyncHandleFrb();

  int crateApiHistoryDeleteReadingByComicIdFrb({required String comicId});

  int crateApiHistoryDeleteReadingByComicIdsFrb({
    required List<String> comicIds,
  });

  int crateApiHistoryDeleteSeriesReadingByLastReadComicIdsFrb({
    required List<String> comicIds,
  });

  int crateApiHistoryDeleteSeriesReadingByNameFrb({required String seriesName});

  PagedComicResultDto crateApiComicFetchComicsPageFrb({
    required PageRequestDto request,
    required ComicFilterDto filter,
    required ComicSortOptionDto sort,
  });

  PagedReadingHistoryDto crateApiHistoryFetchReadingPageFrb({
    required int page,
    required int pageSize,
  });

  PagedSeriesReadingHistoryDto crateApiHistoryFetchSeriesReadingPageFrb({
    required int page,
    required int pageSize,
  });

  ComicDto? crateApiComicFindComicByIdFrb({required String comicId});

  HomePageCountsDto crateApiHomeGetHomePageCountsFrb({
    required bool excludeR18,
  });

  ReadingHistoryDto? crateApiHistoryGetReadingByComicIdFrb({
    required String comicId,
  });

  SeriesReadingHistoryDto? crateApiHistoryGetSeriesReadingByNameFrb({
    required String seriesName,
  });

  InferSeriesResultDto crateApiSeriesInferSeriesFrb();

  Future<void> crateApiComicInitApp();

  void crateApiComicInitDbFrb({
    required String appDataDir,
    required String dbFileName,
  });

  Uint8List crateApiReaderLoadPageBytesFrb({
    required String comicId,
    required String path,
    required String resourceType,
    required int pageIndex,
  });

  ReaderPageListDto crateApiReaderLoadPageListFrb({
    required String comicId,
    required String path,
    required String resourceType,
  });

  void crateApiReaderOpenReaderFrb({
    required String comicId,
    required String path,
    required String resourceType,
  });

  void crateApiHistoryRecordReadingFrb({required ReadingHistoryDto history});

  void crateApiHistoryRecordSeriesReadingFrb({
    required SeriesReadingHistoryDto history,
  });

  List<ComicDto> crateApiComicSearchByKeywordFrb({required String keyword});

  Stream<SyncLibraryProgressDto> crateApiSyncSyncLibraryFrb({
    required SyncHandleDto handle,
  });

  Stream<int> crateApiComicWatchComicChanges();

  Stream<HomePageCountsDto> crateApiHomeWatchHomePageCountsFrb({
    required bool excludeR18,
  });

  Stream<List<ReadingHistoryDto>> crateApiHistoryWatchReadingHistoriesFrb();

  Stream<List<SeriesReadingHistoryDto>>
  crateApiHistoryWatchSeriesReadingHistoriesFrb();

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_SyncHandleDto;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_SyncHandleDto;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_SyncHandleDtoPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  void crateApiSyncCancelSyncFrb({required SyncHandleDto handle}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncHandleDto(
            handle,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSyncCancelSyncFrbConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSyncCancelSyncFrbConstMeta =>
      const TaskConstMeta(debugName: "cancel_sync_frb", argNames: ["handle"]);

  @override
  int crateApiHistoryClearAllReadingFrb() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: sse_decode_hentai_error_dto,
        ),
        constMeta: kCrateApiHistoryClearAllReadingFrbConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHistoryClearAllReadingFrbConstMeta =>
      const TaskConstMeta(debugName: "clear_all_reading_frb", argNames: []);

  @override
  void crateApiReaderClearReaderSessionsFrb() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiReaderClearReaderSessionsFrbConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReaderClearReaderSessionsFrbConstMeta =>
      const TaskConstMeta(debugName: "clear_reader_sessions_frb", argNames: []);

  @override
  void crateApiReaderCloseReaderFrb({required String comicId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(comicId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiReaderCloseReaderFrbConstMeta,
        argValues: [comicId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReaderCloseReaderFrbConstMeta =>
      const TaskConstMeta(debugName: "close_reader_frb", argNames: ["comicId"]);

  @override
  String crateApiComicComicIdFromPathFrb({required String rawPath}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(rawPath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiComicComicIdFromPathFrbConstMeta,
        argValues: [rawPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiComicComicIdFromPathFrbConstMeta =>
      const TaskConstMeta(
        debugName: "comic_id_from_path_frb",
        argNames: ["rawPath"],
      );

  @override
  PlatformInt64 crateApiComicCountAllComicsFrb() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_hentai_error_dto,
        ),
        constMeta: kCrateApiComicCountAllComicsFrbConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiComicCountAllComicsFrbConstMeta =>
      const TaskConstMeta(debugName: "count_all_comics_frb", argNames: []);

  @override
  SyncHandleDto crateApiSyncCreateSyncHandleFrb() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncHandleDto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSyncCreateSyncHandleFrbConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSyncCreateSyncHandleFrbConstMeta =>
      const TaskConstMeta(debugName: "create_sync_handle_frb", argNames: []);

  @override
  int crateApiHistoryDeleteReadingByComicIdFrb({required String comicId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(comicId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: sse_decode_hentai_error_dto,
        ),
        constMeta: kCrateApiHistoryDeleteReadingByComicIdFrbConstMeta,
        argValues: [comicId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHistoryDeleteReadingByComicIdFrbConstMeta =>
      const TaskConstMeta(
        debugName: "delete_reading_by_comic_id_frb",
        argNames: ["comicId"],
      );

  @override
  int crateApiHistoryDeleteReadingByComicIdsFrb({
    required List<String> comicIds,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(comicIds, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: sse_decode_hentai_error_dto,
        ),
        constMeta: kCrateApiHistoryDeleteReadingByComicIdsFrbConstMeta,
        argValues: [comicIds],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHistoryDeleteReadingByComicIdsFrbConstMeta =>
      const TaskConstMeta(
        debugName: "delete_reading_by_comic_ids_frb",
        argNames: ["comicIds"],
      );

  @override
  int crateApiHistoryDeleteSeriesReadingByLastReadComicIdsFrb({
    required List<String> comicIds,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(comicIds, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: sse_decode_hentai_error_dto,
        ),
        constMeta:
            kCrateApiHistoryDeleteSeriesReadingByLastReadComicIdsFrbConstMeta,
        argValues: [comicIds],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiHistoryDeleteSeriesReadingByLastReadComicIdsFrbConstMeta =>
      const TaskConstMeta(
        debugName: "delete_series_reading_by_last_read_comic_ids_frb",
        argNames: ["comicIds"],
      );

  @override
  int crateApiHistoryDeleteSeriesReadingByNameFrb({
    required String seriesName,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(seriesName, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: sse_decode_hentai_error_dto,
        ),
        constMeta: kCrateApiHistoryDeleteSeriesReadingByNameFrbConstMeta,
        argValues: [seriesName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHistoryDeleteSeriesReadingByNameFrbConstMeta =>
      const TaskConstMeta(
        debugName: "delete_series_reading_by_name_frb",
        argNames: ["seriesName"],
      );

  @override
  PagedComicResultDto crateApiComicFetchComicsPageFrb({
    required PageRequestDto request,
    required ComicFilterDto filter,
    required ComicSortOptionDto sort,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_page_request_dto(request, serializer);
          sse_encode_box_autoadd_comic_filter_dto(filter, serializer);
          sse_encode_box_autoadd_comic_sort_option_dto(sort, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_paged_comic_result_dto,
          decodeErrorData: sse_decode_hentai_error_dto,
        ),
        constMeta: kCrateApiComicFetchComicsPageFrbConstMeta,
        argValues: [request, filter, sort],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiComicFetchComicsPageFrbConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_comics_page_frb",
        argNames: ["request", "filter", "sort"],
      );

  @override
  PagedReadingHistoryDto crateApiHistoryFetchReadingPageFrb({
    required int page,
    required int pageSize,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_32(page, serializer);
          sse_encode_i_32(pageSize, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_paged_reading_history_dto,
          decodeErrorData: sse_decode_hentai_error_dto,
        ),
        constMeta: kCrateApiHistoryFetchReadingPageFrbConstMeta,
        argValues: [page, pageSize],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHistoryFetchReadingPageFrbConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_reading_page_frb",
        argNames: ["page", "pageSize"],
      );

  @override
  PagedSeriesReadingHistoryDto crateApiHistoryFetchSeriesReadingPageFrb({
    required int page,
    required int pageSize,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_32(page, serializer);
          sse_encode_i_32(pageSize, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_paged_series_reading_history_dto,
          decodeErrorData: sse_decode_hentai_error_dto,
        ),
        constMeta: kCrateApiHistoryFetchSeriesReadingPageFrbConstMeta,
        argValues: [page, pageSize],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHistoryFetchSeriesReadingPageFrbConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_series_reading_page_frb",
        argNames: ["page", "pageSize"],
      );

  @override
  ComicDto? crateApiComicFindComicByIdFrb({required String comicId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(comicId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_comic_dto,
          decodeErrorData: sse_decode_hentai_error_dto,
        ),
        constMeta: kCrateApiComicFindComicByIdFrbConstMeta,
        argValues: [comicId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiComicFindComicByIdFrbConstMeta =>
      const TaskConstMeta(
        debugName: "find_comic_by_id_frb",
        argNames: ["comicId"],
      );

  @override
  HomePageCountsDto crateApiHomeGetHomePageCountsFrb({
    required bool excludeR18,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(excludeR18, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_home_page_counts_dto,
          decodeErrorData: sse_decode_hentai_error_dto,
        ),
        constMeta: kCrateApiHomeGetHomePageCountsFrbConstMeta,
        argValues: [excludeR18],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHomeGetHomePageCountsFrbConstMeta =>
      const TaskConstMeta(
        debugName: "get_home_page_counts_frb",
        argNames: ["excludeR18"],
      );

  @override
  ReadingHistoryDto? crateApiHistoryGetReadingByComicIdFrb({
    required String comicId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(comicId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_reading_history_dto,
          decodeErrorData: sse_decode_hentai_error_dto,
        ),
        constMeta: kCrateApiHistoryGetReadingByComicIdFrbConstMeta,
        argValues: [comicId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHistoryGetReadingByComicIdFrbConstMeta =>
      const TaskConstMeta(
        debugName: "get_reading_by_comic_id_frb",
        argNames: ["comicId"],
      );

  @override
  SeriesReadingHistoryDto? crateApiHistoryGetSeriesReadingByNameFrb({
    required String seriesName,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(seriesName, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_opt_box_autoadd_series_reading_history_dto,
          decodeErrorData: sse_decode_hentai_error_dto,
        ),
        constMeta: kCrateApiHistoryGetSeriesReadingByNameFrbConstMeta,
        argValues: [seriesName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHistoryGetSeriesReadingByNameFrbConstMeta =>
      const TaskConstMeta(
        debugName: "get_series_reading_by_name_frb",
        argNames: ["seriesName"],
      );

  @override
  InferSeriesResultDto crateApiSeriesInferSeriesFrb() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_infer_series_result_dto,
          decodeErrorData: sse_decode_hentai_error_dto,
        ),
        constMeta: kCrateApiSeriesInferSeriesFrbConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSeriesInferSeriesFrbConstMeta =>
      const TaskConstMeta(debugName: "infer_series_frb", argNames: []);

  @override
  Future<void> crateApiComicInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiComicInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiComicInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  void crateApiComicInitDbFrb({
    required String appDataDir,
    required String dbFileName,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(appDataDir, serializer);
          sse_encode_String(dbFileName, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_hentai_error_dto,
        ),
        constMeta: kCrateApiComicInitDbFrbConstMeta,
        argValues: [appDataDir, dbFileName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiComicInitDbFrbConstMeta => const TaskConstMeta(
    debugName: "init_db_frb",
    argNames: ["appDataDir", "dbFileName"],
  );

  @override
  Uint8List crateApiReaderLoadPageBytesFrb({
    required String comicId,
    required String path,
    required String resourceType,
    required int pageIndex,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(comicId, serializer);
          sse_encode_String(path, serializer);
          sse_encode_String(resourceType, serializer);
          sse_encode_i_32(pageIndex, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_hentai_error_dto,
        ),
        constMeta: kCrateApiReaderLoadPageBytesFrbConstMeta,
        argValues: [comicId, path, resourceType, pageIndex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReaderLoadPageBytesFrbConstMeta =>
      const TaskConstMeta(
        debugName: "load_page_bytes_frb",
        argNames: ["comicId", "path", "resourceType", "pageIndex"],
      );

  @override
  ReaderPageListDto crateApiReaderLoadPageListFrb({
    required String comicId,
    required String path,
    required String resourceType,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(comicId, serializer);
          sse_encode_String(path, serializer);
          sse_encode_String(resourceType, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_reader_page_list_dto,
          decodeErrorData: sse_decode_hentai_error_dto,
        ),
        constMeta: kCrateApiReaderLoadPageListFrbConstMeta,
        argValues: [comicId, path, resourceType],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReaderLoadPageListFrbConstMeta =>
      const TaskConstMeta(
        debugName: "load_page_list_frb",
        argNames: ["comicId", "path", "resourceType"],
      );

  @override
  void crateApiReaderOpenReaderFrb({
    required String comicId,
    required String path,
    required String resourceType,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(comicId, serializer);
          sse_encode_String(path, serializer);
          sse_encode_String(resourceType, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_hentai_error_dto,
        ),
        constMeta: kCrateApiReaderOpenReaderFrbConstMeta,
        argValues: [comicId, path, resourceType],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReaderOpenReaderFrbConstMeta =>
      const TaskConstMeta(
        debugName: "open_reader_frb",
        argNames: ["comicId", "path", "resourceType"],
      );

  @override
  void crateApiHistoryRecordReadingFrb({required ReadingHistoryDto history}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_reading_history_dto(history, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_hentai_error_dto,
        ),
        constMeta: kCrateApiHistoryRecordReadingFrbConstMeta,
        argValues: [history],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHistoryRecordReadingFrbConstMeta =>
      const TaskConstMeta(
        debugName: "record_reading_frb",
        argNames: ["history"],
      );

  @override
  void crateApiHistoryRecordSeriesReadingFrb({
    required SeriesReadingHistoryDto history,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_series_reading_history_dto(
            history,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 26)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_hentai_error_dto,
        ),
        constMeta: kCrateApiHistoryRecordSeriesReadingFrbConstMeta,
        argValues: [history],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHistoryRecordSeriesReadingFrbConstMeta =>
      const TaskConstMeta(
        debugName: "record_series_reading_frb",
        argNames: ["history"],
      );

  @override
  List<ComicDto> crateApiComicSearchByKeywordFrb({required String keyword}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(keyword, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 27)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_comic_dto,
          decodeErrorData: sse_decode_hentai_error_dto,
        ),
        constMeta: kCrateApiComicSearchByKeywordFrbConstMeta,
        argValues: [keyword],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiComicSearchByKeywordFrbConstMeta =>
      const TaskConstMeta(
        debugName: "search_by_keyword_frb",
        argNames: ["keyword"],
      );

  @override
  Stream<SyncLibraryProgressDto> crateApiSyncSyncLibraryFrb({
    required SyncHandleDto handle,
  }) {
    final sink = RustStreamSink<SyncLibraryProgressDto>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncHandleDto(
              handle,
              serializer,
            );
            sse_encode_StreamSink_sync_library_progress_dto_Sse(
              sink,
              serializer,
            );
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 28,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_hentai_error_dto,
          ),
          constMeta: kCrateApiSyncSyncLibraryFrbConstMeta,
          argValues: [handle, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSyncSyncLibraryFrbConstMeta => const TaskConstMeta(
    debugName: "sync_library_frb",
    argNames: ["handle", "sink"],
  );

  @override
  Stream<int> crateApiComicWatchComicChanges() {
    final sink = RustStreamSink<int>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_i_32_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 29,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_hentai_error_dto,
          ),
          constMeta: kCrateApiComicWatchComicChangesConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiComicWatchComicChangesConstMeta =>
      const TaskConstMeta(debugName: "watch_comic_changes", argNames: ["sink"]);

  @override
  Stream<HomePageCountsDto> crateApiHomeWatchHomePageCountsFrb({
    required bool excludeR18,
  }) {
    final sink = RustStreamSink<HomePageCountsDto>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_bool(excludeR18, serializer);
            sse_encode_StreamSink_home_page_counts_dto_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 30,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_hentai_error_dto,
          ),
          constMeta: kCrateApiHomeWatchHomePageCountsFrbConstMeta,
          argValues: [excludeR18, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiHomeWatchHomePageCountsFrbConstMeta =>
      const TaskConstMeta(
        debugName: "watch_home_page_counts_frb",
        argNames: ["excludeR18", "sink"],
      );

  @override
  Stream<List<ReadingHistoryDto>> crateApiHistoryWatchReadingHistoriesFrb() {
    final sink = RustStreamSink<List<ReadingHistoryDto>>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_list_reading_history_dto_Sse(
              sink,
              serializer,
            );
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 31,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_hentai_error_dto,
          ),
          constMeta: kCrateApiHistoryWatchReadingHistoriesFrbConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiHistoryWatchReadingHistoriesFrbConstMeta =>
      const TaskConstMeta(
        debugName: "watch_reading_histories_frb",
        argNames: ["sink"],
      );

  @override
  Stream<List<SeriesReadingHistoryDto>>
  crateApiHistoryWatchSeriesReadingHistoriesFrb() {
    final sink = RustStreamSink<List<SeriesReadingHistoryDto>>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_list_series_reading_history_dto_Sse(
              sink,
              serializer,
            );
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 32,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_hentai_error_dto,
          ),
          constMeta: kCrateApiHistoryWatchSeriesReadingHistoriesFrbConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiHistoryWatchSeriesReadingHistoriesFrbConstMeta =>
      const TaskConstMeta(
        debugName: "watch_series_reading_histories_frb",
        argNames: ["sink"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_SyncHandleDto => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncHandleDto;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_SyncHandleDto => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncHandleDto;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  SyncHandleDto
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncHandleDto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SyncHandleDtoImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SyncHandleDto
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncHandleDto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SyncHandleDtoImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SyncHandleDto
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncHandleDto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SyncHandleDtoImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<HomePageCountsDto>
  dco_decode_StreamSink_home_page_counts_dto_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<int> dco_decode_StreamSink_i_32_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<List<ReadingHistoryDto>>
  dco_decode_StreamSink_list_reading_history_dto_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<List<SeriesReadingHistoryDto>>
  dco_decode_StreamSink_list_series_reading_history_dto_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<SyncLibraryProgressDto>
  dco_decode_StreamSink_sync_library_progress_dto_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ComicDto dco_decode_box_autoadd_comic_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_comic_dto(raw);
  }

  @protected
  ComicFilterDto dco_decode_box_autoadd_comic_filter_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_comic_filter_dto(raw);
  }

  @protected
  ComicSortOptionDto dco_decode_box_autoadd_comic_sort_option_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_comic_sort_option_dto(raw);
  }

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PageRequestDto dco_decode_box_autoadd_page_request_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_page_request_dto(raw);
  }

  @protected
  ReadingHistoryDto dco_decode_box_autoadd_reading_history_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_reading_history_dto(raw);
  }

  @protected
  SeriesReadingHistoryDto dco_decode_box_autoadd_series_reading_history_dto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_series_reading_history_dto(raw);
  }

  @protected
  ComicDto dco_decode_comic_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return ComicDto(
      comicId: dco_decode_String(arr[0]),
      path: dco_decode_String(arr[1]),
      resourceType: dco_decode_String(arr[2]),
      title: dco_decode_String(arr[3]),
      contentRating: dco_decode_String(arr[4]),
      pageCount: dco_decode_opt_box_autoadd_i_32(arr[5]),
      authors: dco_decode_list_String(arr[6]),
      tags: dco_decode_list_String(arr[7]),
    );
  }

  @protected
  ComicFilterDto dco_decode_comic_filter_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return ComicFilterDto(
      showR18: dco_decode_bool(arr[0]),
      query: dco_decode_opt_String(arr[1]),
      resourceTypes: dco_decode_list_String(arr[2]),
      contentRatings: dco_decode_list_String(arr[3]),
      tagsAll: dco_decode_list_String(arr[4]),
      tagsAny: dco_decode_list_String(arr[5]),
      tagsExclude: dco_decode_list_String(arr[6]),
      excludeComicsInAnySeries: dco_decode_bool(arr[7]),
    );
  }

  @protected
  ComicSortOptionDto dco_decode_comic_sort_option_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return ComicSortOptionDto(descending: dco_decode_bool(arr[0]));
  }

  @protected
  HentaiErrorDto dco_decode_hentai_error_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return HentaiErrorDto(
      code: dco_decode_String(arr[0]),
      message: dco_decode_String(arr[1]),
      context: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  HomePageCountsDto dco_decode_home_page_counts_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return HomePageCountsDto(
      comicCount: dco_decode_i_32(arr[0]),
      tagCount: dco_decode_i_32(arr[1]),
      seriesCount: dco_decode_i_32(arr[2]),
      readingRecordCount: dco_decode_i_32(arr[3]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  InferSeriesResultDto dco_decode_infer_series_result_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return InferSeriesResultDto(
      groupsApplied: dco_decode_i_32(arr[0]),
      comicsAssigned: dco_decode_i_32(arr[1]),
      newSeriesCreated: dco_decode_i_32(arr[2]),
    );
  }

  @protected
  LibrarySyncCountsDto dco_decode_library_sync_counts_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return LibrarySyncCountsDto(
      dir: dco_decode_i_32(arr[0]),
      zip: dco_decode_i_32(arr[1]),
      cbz: dco_decode_i_32(arr[2]),
      epub: dco_decode_i_32(arr[3]),
      cbr: dco_decode_i_32(arr[4]),
      rar: dco_decode_i_32(arr[5]),
      cb7: dco_decode_i_32(arr[6]),
      sevenz: dco_decode_i_32(arr[7]),
      pdf: dco_decode_i_32(arr[8]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<ComicDto> dco_decode_list_comic_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_comic_dto).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<ReadingHistoryDto> dco_decode_list_reading_history_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_reading_history_dto).toList();
  }

  @protected
  List<SeriesReadingHistoryDto> dco_decode_list_series_reading_history_dto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_series_reading_history_dto)
        .toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  ComicDto? dco_decode_opt_box_autoadd_comic_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_comic_dto(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_32(raw);
  }

  @protected
  ReadingHistoryDto? dco_decode_opt_box_autoadd_reading_history_dto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_reading_history_dto(raw);
  }

  @protected
  SeriesReadingHistoryDto?
  dco_decode_opt_box_autoadd_series_reading_history_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_series_reading_history_dto(raw);
  }

  @protected
  PageRequestDto dco_decode_page_request_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return PageRequestDto(
      page: dco_decode_i_32(arr[0]),
      pageSize: dco_decode_i_32(arr[1]),
    );
  }

  @protected
  PagedComicResultDto dco_decode_paged_comic_result_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return PagedComicResultDto(
      items: dco_decode_list_comic_dto(arr[0]),
      totalCount: dco_decode_i_64(arr[1]),
      page: dco_decode_i_32(arr[2]),
      pageSize: dco_decode_i_32(arr[3]),
    );
  }

  @protected
  PagedReadingHistoryDto dco_decode_paged_reading_history_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return PagedReadingHistoryDto(
      items: dco_decode_list_reading_history_dto(arr[0]),
      totalCount: dco_decode_i_64(arr[1]),
    );
  }

  @protected
  PagedSeriesReadingHistoryDto dco_decode_paged_series_reading_history_dto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return PagedSeriesReadingHistoryDto(
      items: dco_decode_list_series_reading_history_dto(arr[0]),
      totalCount: dco_decode_i_64(arr[1]),
    );
  }

  @protected
  ReaderPageListDto dco_decode_reader_page_list_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ReaderPageListDto(
      resourceType: dco_decode_String(arr[0]),
      pageCount: dco_decode_i_32(arr[1]),
      dirPagePaths: dco_decode_list_String(arr[2]),
    );
  }

  @protected
  ReadingHistoryDto dco_decode_reading_history_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ReadingHistoryDto(
      comicId: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      lastReadTimeMs: dco_decode_i_64(arr[2]),
      pageIndex: dco_decode_opt_box_autoadd_i_32(arr[3]),
    );
  }

  @protected
  SeriesReadingHistoryDto dco_decode_series_reading_history_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SeriesReadingHistoryDto(
      seriesName: dco_decode_String(arr[0]),
      lastReadComicId: dco_decode_String(arr[1]),
      lastReadTimeMs: dco_decode_i_64(arr[2]),
      pageIndex: dco_decode_opt_box_autoadd_i_32(arr[3]),
    );
  }

  @protected
  SyncLibraryPhaseDto dco_decode_sync_library_phase_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SyncLibraryPhaseDto.values[raw as int];
  }

  @protected
  SyncLibraryProgressDto dco_decode_sync_library_progress_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return SyncLibraryProgressDto(
      phase: dco_decode_sync_library_phase_dto(arr[0]),
      route: dco_decode_sync_library_route_dto(arr[1]),
      currentPath: dco_decode_opt_String(arr[2]),
      acceptedTotal: dco_decode_i_32(arr[3]),
      counts: dco_decode_library_sync_counts_dto(arr[4]),
      removedCount: dco_decode_opt_box_autoadd_i_32(arr[5]),
      addedCount: dco_decode_opt_box_autoadd_i_32(arr[6]),
      keptCount: dco_decode_opt_box_autoadd_i_32(arr[7]),
      thumbnailTotal: dco_decode_opt_box_autoadd_i_32(arr[8]),
      thumbnailDone: dco_decode_opt_box_autoadd_i_32(arr[9]),
      thumbnailFailedCount: dco_decode_opt_box_autoadd_i_32(arr[10]),
    );
  }

  @protected
  SyncLibraryRouteDto dco_decode_sync_library_route_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SyncLibraryRouteDto.values[raw as int];
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  SyncHandleDto
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncHandleDto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SyncHandleDtoImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SyncHandleDto
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncHandleDto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SyncHandleDtoImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SyncHandleDto
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncHandleDto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SyncHandleDtoImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustStreamSink<HomePageCountsDto>
  sse_decode_StreamSink_home_page_counts_dto_Sse(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<int> sse_decode_StreamSink_i_32_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<List<ReadingHistoryDto>>
  sse_decode_StreamSink_list_reading_history_dto_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<List<SeriesReadingHistoryDto>>
  sse_decode_StreamSink_list_series_reading_history_dto_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<SyncLibraryProgressDto>
  sse_decode_StreamSink_sync_library_progress_dto_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ComicDto sse_decode_box_autoadd_comic_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_comic_dto(deserializer));
  }

  @protected
  ComicFilterDto sse_decode_box_autoadd_comic_filter_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_comic_filter_dto(deserializer));
  }

  @protected
  ComicSortOptionDto sse_decode_box_autoadd_comic_sort_option_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_comic_sort_option_dto(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_32(deserializer));
  }

  @protected
  PageRequestDto sse_decode_box_autoadd_page_request_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_page_request_dto(deserializer));
  }

  @protected
  ReadingHistoryDto sse_decode_box_autoadd_reading_history_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_reading_history_dto(deserializer));
  }

  @protected
  SeriesReadingHistoryDto sse_decode_box_autoadd_series_reading_history_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_series_reading_history_dto(deserializer));
  }

  @protected
  ComicDto sse_decode_comic_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_comicId = sse_decode_String(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_resourceType = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_contentRating = sse_decode_String(deserializer);
    var var_pageCount = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_authors = sse_decode_list_String(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    return ComicDto(
      comicId: var_comicId,
      path: var_path,
      resourceType: var_resourceType,
      title: var_title,
      contentRating: var_contentRating,
      pageCount: var_pageCount,
      authors: var_authors,
      tags: var_tags,
    );
  }

  @protected
  ComicFilterDto sse_decode_comic_filter_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_showR18 = sse_decode_bool(deserializer);
    var var_query = sse_decode_opt_String(deserializer);
    var var_resourceTypes = sse_decode_list_String(deserializer);
    var var_contentRatings = sse_decode_list_String(deserializer);
    var var_tagsAll = sse_decode_list_String(deserializer);
    var var_tagsAny = sse_decode_list_String(deserializer);
    var var_tagsExclude = sse_decode_list_String(deserializer);
    var var_excludeComicsInAnySeries = sse_decode_bool(deserializer);
    return ComicFilterDto(
      showR18: var_showR18,
      query: var_query,
      resourceTypes: var_resourceTypes,
      contentRatings: var_contentRatings,
      tagsAll: var_tagsAll,
      tagsAny: var_tagsAny,
      tagsExclude: var_tagsExclude,
      excludeComicsInAnySeries: var_excludeComicsInAnySeries,
    );
  }

  @protected
  ComicSortOptionDto sse_decode_comic_sort_option_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_descending = sse_decode_bool(deserializer);
    return ComicSortOptionDto(descending: var_descending);
  }

  @protected
  HentaiErrorDto sse_decode_hentai_error_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_code = sse_decode_String(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_context = sse_decode_opt_String(deserializer);
    return HentaiErrorDto(
      code: var_code,
      message: var_message,
      context: var_context,
    );
  }

  @protected
  HomePageCountsDto sse_decode_home_page_counts_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_comicCount = sse_decode_i_32(deserializer);
    var var_tagCount = sse_decode_i_32(deserializer);
    var var_seriesCount = sse_decode_i_32(deserializer);
    var var_readingRecordCount = sse_decode_i_32(deserializer);
    return HomePageCountsDto(
      comicCount: var_comicCount,
      tagCount: var_tagCount,
      seriesCount: var_seriesCount,
      readingRecordCount: var_readingRecordCount,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  InferSeriesResultDto sse_decode_infer_series_result_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_groupsApplied = sse_decode_i_32(deserializer);
    var var_comicsAssigned = sse_decode_i_32(deserializer);
    var var_newSeriesCreated = sse_decode_i_32(deserializer);
    return InferSeriesResultDto(
      groupsApplied: var_groupsApplied,
      comicsAssigned: var_comicsAssigned,
      newSeriesCreated: var_newSeriesCreated,
    );
  }

  @protected
  LibrarySyncCountsDto sse_decode_library_sync_counts_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_dir = sse_decode_i_32(deserializer);
    var var_zip = sse_decode_i_32(deserializer);
    var var_cbz = sse_decode_i_32(deserializer);
    var var_epub = sse_decode_i_32(deserializer);
    var var_cbr = sse_decode_i_32(deserializer);
    var var_rar = sse_decode_i_32(deserializer);
    var var_cb7 = sse_decode_i_32(deserializer);
    var var_sevenz = sse_decode_i_32(deserializer);
    var var_pdf = sse_decode_i_32(deserializer);
    return LibrarySyncCountsDto(
      dir: var_dir,
      zip: var_zip,
      cbz: var_cbz,
      epub: var_epub,
      cbr: var_cbr,
      rar: var_rar,
      cb7: var_cb7,
      sevenz: var_sevenz,
      pdf: var_pdf,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<ComicDto> sse_decode_list_comic_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ComicDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_comic_dto(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<ReadingHistoryDto> sse_decode_list_reading_history_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ReadingHistoryDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_reading_history_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<SeriesReadingHistoryDto> sse_decode_list_series_reading_history_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SeriesReadingHistoryDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_series_reading_history_dto(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ComicDto? sse_decode_opt_box_autoadd_comic_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_comic_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ReadingHistoryDto? sse_decode_opt_box_autoadd_reading_history_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_reading_history_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SeriesReadingHistoryDto?
  sse_decode_opt_box_autoadd_series_reading_history_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_series_reading_history_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PageRequestDto sse_decode_page_request_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_page = sse_decode_i_32(deserializer);
    var var_pageSize = sse_decode_i_32(deserializer);
    return PageRequestDto(page: var_page, pageSize: var_pageSize);
  }

  @protected
  PagedComicResultDto sse_decode_paged_comic_result_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_items = sse_decode_list_comic_dto(deserializer);
    var var_totalCount = sse_decode_i_64(deserializer);
    var var_page = sse_decode_i_32(deserializer);
    var var_pageSize = sse_decode_i_32(deserializer);
    return PagedComicResultDto(
      items: var_items,
      totalCount: var_totalCount,
      page: var_page,
      pageSize: var_pageSize,
    );
  }

  @protected
  PagedReadingHistoryDto sse_decode_paged_reading_history_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_items = sse_decode_list_reading_history_dto(deserializer);
    var var_totalCount = sse_decode_i_64(deserializer);
    return PagedReadingHistoryDto(items: var_items, totalCount: var_totalCount);
  }

  @protected
  PagedSeriesReadingHistoryDto sse_decode_paged_series_reading_history_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_items = sse_decode_list_series_reading_history_dto(deserializer);
    var var_totalCount = sse_decode_i_64(deserializer);
    return PagedSeriesReadingHistoryDto(
      items: var_items,
      totalCount: var_totalCount,
    );
  }

  @protected
  ReaderPageListDto sse_decode_reader_page_list_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_resourceType = sse_decode_String(deserializer);
    var var_pageCount = sse_decode_i_32(deserializer);
    var var_dirPagePaths = sse_decode_list_String(deserializer);
    return ReaderPageListDto(
      resourceType: var_resourceType,
      pageCount: var_pageCount,
      dirPagePaths: var_dirPagePaths,
    );
  }

  @protected
  ReadingHistoryDto sse_decode_reading_history_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_comicId = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_lastReadTimeMs = sse_decode_i_64(deserializer);
    var var_pageIndex = sse_decode_opt_box_autoadd_i_32(deserializer);
    return ReadingHistoryDto(
      comicId: var_comicId,
      title: var_title,
      lastReadTimeMs: var_lastReadTimeMs,
      pageIndex: var_pageIndex,
    );
  }

  @protected
  SeriesReadingHistoryDto sse_decode_series_reading_history_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_seriesName = sse_decode_String(deserializer);
    var var_lastReadComicId = sse_decode_String(deserializer);
    var var_lastReadTimeMs = sse_decode_i_64(deserializer);
    var var_pageIndex = sse_decode_opt_box_autoadd_i_32(deserializer);
    return SeriesReadingHistoryDto(
      seriesName: var_seriesName,
      lastReadComicId: var_lastReadComicId,
      lastReadTimeMs: var_lastReadTimeMs,
      pageIndex: var_pageIndex,
    );
  }

  @protected
  SyncLibraryPhaseDto sse_decode_sync_library_phase_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SyncLibraryPhaseDto.values[inner];
  }

  @protected
  SyncLibraryProgressDto sse_decode_sync_library_progress_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_phase = sse_decode_sync_library_phase_dto(deserializer);
    var var_route = sse_decode_sync_library_route_dto(deserializer);
    var var_currentPath = sse_decode_opt_String(deserializer);
    var var_acceptedTotal = sse_decode_i_32(deserializer);
    var var_counts = sse_decode_library_sync_counts_dto(deserializer);
    var var_removedCount = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_addedCount = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_keptCount = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_thumbnailTotal = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_thumbnailDone = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_thumbnailFailedCount = sse_decode_opt_box_autoadd_i_32(
      deserializer,
    );
    return SyncLibraryProgressDto(
      phase: var_phase,
      route: var_route,
      currentPath: var_currentPath,
      acceptedTotal: var_acceptedTotal,
      counts: var_counts,
      removedCount: var_removedCount,
      addedCount: var_addedCount,
      keptCount: var_keptCount,
      thumbnailTotal: var_thumbnailTotal,
      thumbnailDone: var_thumbnailDone,
      thumbnailFailedCount: var_thumbnailFailedCount,
    );
  }

  @protected
  SyncLibraryRouteDto sse_decode_sync_library_route_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SyncLibraryRouteDto.values[inner];
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncHandleDto(
    SyncHandleDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SyncHandleDtoImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncHandleDto(
    SyncHandleDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SyncHandleDtoImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncHandleDto(
    SyncHandleDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SyncHandleDtoImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_home_page_counts_dto_Sse(
    RustStreamSink<HomePageCountsDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_home_page_counts_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_i_32_Sse(
    RustStreamSink<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_list_reading_history_dto_Sse(
    RustStreamSink<List<ReadingHistoryDto>> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_reading_history_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_list_series_reading_history_dto_Sse(
    RustStreamSink<List<SeriesReadingHistoryDto>> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_series_reading_history_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_sync_library_progress_dto_Sse(
    RustStreamSink<SyncLibraryProgressDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_sync_library_progress_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_comic_dto(
    ComicDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_comic_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_comic_filter_dto(
    ComicFilterDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_comic_filter_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_comic_sort_option_dto(
    ComicSortOptionDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_comic_sort_option_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_page_request_dto(
    PageRequestDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_page_request_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_reading_history_dto(
    ReadingHistoryDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_reading_history_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_series_reading_history_dto(
    SeriesReadingHistoryDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_series_reading_history_dto(self, serializer);
  }

  @protected
  void sse_encode_comic_dto(ComicDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.comicId, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_String(self.resourceType, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.contentRating, serializer);
    sse_encode_opt_box_autoadd_i_32(self.pageCount, serializer);
    sse_encode_list_String(self.authors, serializer);
    sse_encode_list_String(self.tags, serializer);
  }

  @protected
  void sse_encode_comic_filter_dto(
    ComicFilterDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.showR18, serializer);
    sse_encode_opt_String(self.query, serializer);
    sse_encode_list_String(self.resourceTypes, serializer);
    sse_encode_list_String(self.contentRatings, serializer);
    sse_encode_list_String(self.tagsAll, serializer);
    sse_encode_list_String(self.tagsAny, serializer);
    sse_encode_list_String(self.tagsExclude, serializer);
    sse_encode_bool(self.excludeComicsInAnySeries, serializer);
  }

  @protected
  void sse_encode_comic_sort_option_dto(
    ComicSortOptionDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.descending, serializer);
  }

  @protected
  void sse_encode_hentai_error_dto(
    HentaiErrorDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.code, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_opt_String(self.context, serializer);
  }

  @protected
  void sse_encode_home_page_counts_dto(
    HomePageCountsDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.comicCount, serializer);
    sse_encode_i_32(self.tagCount, serializer);
    sse_encode_i_32(self.seriesCount, serializer);
    sse_encode_i_32(self.readingRecordCount, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_infer_series_result_dto(
    InferSeriesResultDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.groupsApplied, serializer);
    sse_encode_i_32(self.comicsAssigned, serializer);
    sse_encode_i_32(self.newSeriesCreated, serializer);
  }

  @protected
  void sse_encode_library_sync_counts_dto(
    LibrarySyncCountsDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.dir, serializer);
    sse_encode_i_32(self.zip, serializer);
    sse_encode_i_32(self.cbz, serializer);
    sse_encode_i_32(self.epub, serializer);
    sse_encode_i_32(self.cbr, serializer);
    sse_encode_i_32(self.rar, serializer);
    sse_encode_i_32(self.cb7, serializer);
    sse_encode_i_32(self.sevenz, serializer);
    sse_encode_i_32(self.pdf, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_comic_dto(
    List<ComicDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_comic_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_reading_history_dto(
    List<ReadingHistoryDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_reading_history_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_series_reading_history_dto(
    List<SeriesReadingHistoryDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_series_reading_history_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_comic_dto(
    ComicDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_comic_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_reading_history_dto(
    ReadingHistoryDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_reading_history_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_series_reading_history_dto(
    SeriesReadingHistoryDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_series_reading_history_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_page_request_dto(
    PageRequestDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.page, serializer);
    sse_encode_i_32(self.pageSize, serializer);
  }

  @protected
  void sse_encode_paged_comic_result_dto(
    PagedComicResultDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_comic_dto(self.items, serializer);
    sse_encode_i_64(self.totalCount, serializer);
    sse_encode_i_32(self.page, serializer);
    sse_encode_i_32(self.pageSize, serializer);
  }

  @protected
  void sse_encode_paged_reading_history_dto(
    PagedReadingHistoryDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_reading_history_dto(self.items, serializer);
    sse_encode_i_64(self.totalCount, serializer);
  }

  @protected
  void sse_encode_paged_series_reading_history_dto(
    PagedSeriesReadingHistoryDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_series_reading_history_dto(self.items, serializer);
    sse_encode_i_64(self.totalCount, serializer);
  }

  @protected
  void sse_encode_reader_page_list_dto(
    ReaderPageListDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.resourceType, serializer);
    sse_encode_i_32(self.pageCount, serializer);
    sse_encode_list_String(self.dirPagePaths, serializer);
  }

  @protected
  void sse_encode_reading_history_dto(
    ReadingHistoryDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.comicId, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_i_64(self.lastReadTimeMs, serializer);
    sse_encode_opt_box_autoadd_i_32(self.pageIndex, serializer);
  }

  @protected
  void sse_encode_series_reading_history_dto(
    SeriesReadingHistoryDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.seriesName, serializer);
    sse_encode_String(self.lastReadComicId, serializer);
    sse_encode_i_64(self.lastReadTimeMs, serializer);
    sse_encode_opt_box_autoadd_i_32(self.pageIndex, serializer);
  }

  @protected
  void sse_encode_sync_library_phase_dto(
    SyncLibraryPhaseDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_sync_library_progress_dto(
    SyncLibraryProgressDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_sync_library_phase_dto(self.phase, serializer);
    sse_encode_sync_library_route_dto(self.route, serializer);
    sse_encode_opt_String(self.currentPath, serializer);
    sse_encode_i_32(self.acceptedTotal, serializer);
    sse_encode_library_sync_counts_dto(self.counts, serializer);
    sse_encode_opt_box_autoadd_i_32(self.removedCount, serializer);
    sse_encode_opt_box_autoadd_i_32(self.addedCount, serializer);
    sse_encode_opt_box_autoadd_i_32(self.keptCount, serializer);
    sse_encode_opt_box_autoadd_i_32(self.thumbnailTotal, serializer);
    sse_encode_opt_box_autoadd_i_32(self.thumbnailDone, serializer);
    sse_encode_opt_box_autoadd_i_32(self.thumbnailFailedCount, serializer);
  }

  @protected
  void sse_encode_sync_library_route_dto(
    SyncLibraryRouteDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class SyncHandleDtoImpl extends RustOpaque implements SyncHandleDto {
  // Not to be used by end users
  SyncHandleDtoImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  SyncHandleDtoImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_SyncHandleDto,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_SyncHandleDto,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_SyncHandleDtoPtr,
  );
}
