// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/author.dart';
import 'api/comic.dart';
import 'api/history.dart';
import 'api/home.dart';
import 'api/init.dart';
import 'api/path.dart';
import 'api/reader.dart';
import 'api/series.dart';
import 'api/sync.dart';
import 'api/tag.dart';
import 'api/thumbnail.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_SyncHandleDtoPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncHandleDto;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  SyncHandleDto
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncHandleDto(
    dynamic raw,
  );

  @protected
  SyncHandleDto
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncHandleDto(
    dynamic raw,
  );

  @protected
  SyncHandleDto
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncHandleDto(
    dynamic raw,
  );

  @protected
  RustStreamSink<HomePageCountsDto>
  dco_decode_StreamSink_home_page_counts_dto_Sse(dynamic raw);

  @protected
  RustStreamSink<int> dco_decode_StreamSink_i_32_Sse(dynamic raw);

  @protected
  RustStreamSink<List<String>> dco_decode_StreamSink_list_String_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<List<HomeContinueReadingDto>>
  dco_decode_StreamSink_list_home_continue_reading_dto_Sse(dynamic raw);

  @protected
  RustStreamSink<List<ReadingHistoryDto>>
  dco_decode_StreamSink_list_reading_history_dto_Sse(dynamic raw);

  @protected
  RustStreamSink<List<SeriesComicOrderEntryDto>>
  dco_decode_StreamSink_list_series_comic_order_entry_dto_Sse(dynamic raw);

  @protected
  RustStreamSink<List<SeriesDto>> dco_decode_StreamSink_list_series_dto_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<SyncLibraryProgressDto>
  dco_decode_StreamSink_sync_library_progress_dto_Sse(dynamic raw);

  @protected
  RustStreamSink<ThumbnailEventDto>
  dco_decode_StreamSink_thumbnail_event_dto_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AuthorPagedNamesDto dco_decode_author_paged_names_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ComicDto dco_decode_box_autoadd_comic_dto(dynamic raw);

  @protected
  ComicFilterDto dco_decode_box_autoadd_comic_filter_dto(dynamic raw);

  @protected
  ComicSortOptionDto dco_decode_box_autoadd_comic_sort_option_dto(dynamic raw);

  @protected
  ComicThumbnailDto dco_decode_box_autoadd_comic_thumbnail_dto(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  PageRequestDto dco_decode_box_autoadd_page_request_dto(dynamic raw);

  @protected
  ReadingHistoryDto dco_decode_box_autoadd_reading_history_dto(dynamic raw);

  @protected
  SeriesDto dco_decode_box_autoadd_series_dto(dynamic raw);

  @protected
  SeriesFilterDto dco_decode_box_autoadd_series_filter_dto(dynamic raw);

  @protected
  SeriesReadingHistoryDto dco_decode_box_autoadd_series_reading_history_dto(
    dynamic raw,
  );

  @protected
  SeriesSortOptionDto dco_decode_box_autoadd_series_sort_option_dto(
    dynamic raw,
  );

  @protected
  UpdateComicUserMetaFrbDto
  dco_decode_box_autoadd_update_comic_user_meta_frb_dto(dynamic raw);

  @protected
  UpdateSeriesUserMetaDto dco_decode_box_autoadd_update_series_user_meta_dto(
    dynamic raw,
  );

  @protected
  ComicDto dco_decode_comic_dto(dynamic raw);

  @protected
  ComicFilterDto dco_decode_comic_filter_dto(dynamic raw);

  @protected
  ComicSortOptionDto dco_decode_comic_sort_option_dto(dynamic raw);

  @protected
  ComicThumbnailDto dco_decode_comic_thumbnail_dto(dynamic raw);

  @protected
  HentaiErrorDto dco_decode_hentai_error_dto(dynamic raw);

  @protected
  HomeContinueReadingDto dco_decode_home_continue_reading_dto(dynamic raw);

  @protected
  HomePageCountsDto dco_decode_home_page_counts_dto(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  LibrarySyncCountsDto dco_decode_library_sync_counts_dto(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ComicDto> dco_decode_list_comic_dto(dynamic raw);

  @protected
  List<HomeContinueReadingDto> dco_decode_list_home_continue_reading_dto(
    dynamic raw,
  );

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ReadingHistoryDto> dco_decode_list_reading_history_dto(dynamic raw);

  @protected
  List<SeriesComicOrderEntryDto> dco_decode_list_series_comic_order_entry_dto(
    dynamic raw,
  );

  @protected
  List<SeriesDto> dco_decode_list_series_dto(dynamic raw);

  @protected
  List<SeriesItemDto> dco_decode_list_series_item_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  ComicDto? dco_decode_opt_box_autoadd_comic_dto(dynamic raw);

  @protected
  ComicThumbnailDto? dco_decode_opt_box_autoadd_comic_thumbnail_dto(
    dynamic raw,
  );

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  ReadingHistoryDto? dco_decode_opt_box_autoadd_reading_history_dto(
    dynamic raw,
  );

  @protected
  SeriesDto? dco_decode_opt_box_autoadd_series_dto(dynamic raw);

  @protected
  SeriesReadingHistoryDto?
  dco_decode_opt_box_autoadd_series_reading_history_dto(dynamic raw);

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  PageRequestDto dco_decode_page_request_dto(dynamic raw);

  @protected
  PagedComicResultDto dco_decode_paged_comic_result_dto(dynamic raw);

  @protected
  PagedReadingHistoryDto dco_decode_paged_reading_history_dto(dynamic raw);

  @protected
  PagedSeriesResultDto dco_decode_paged_series_result_dto(dynamic raw);

  @protected
  ReaderPageListDto dco_decode_reader_page_list_dto(dynamic raw);

  @protected
  ReadingHistoryDto dco_decode_reading_history_dto(dynamic raw);

  @protected
  SeriesComicOrderEntryDto dco_decode_series_comic_order_entry_dto(dynamic raw);

  @protected
  SeriesDto dco_decode_series_dto(dynamic raw);

  @protected
  SeriesFilterDto dco_decode_series_filter_dto(dynamic raw);

  @protected
  SeriesItemDto dco_decode_series_item_dto(dynamic raw);

  @protected
  SeriesReadingHistoryDto dco_decode_series_reading_history_dto(dynamic raw);

  @protected
  SeriesSortOptionDto dco_decode_series_sort_option_dto(dynamic raw);

  @protected
  SyncLibraryPhaseDto dco_decode_sync_library_phase_dto(dynamic raw);

  @protected
  SyncLibraryProgressDto dco_decode_sync_library_progress_dto(dynamic raw);

  @protected
  SyncLibraryRouteDto dco_decode_sync_library_route_dto(dynamic raw);

  @protected
  TagPagedNamesDto dco_decode_tag_paged_names_dto(dynamic raw);

  @protected
  ThumbnailEventDto dco_decode_thumbnail_event_dto(dynamic raw);

  @protected
  ThumbnailPriorityDto dco_decode_thumbnail_priority_dto(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UpdateComicUserMetaFrbDto dco_decode_update_comic_user_meta_frb_dto(
    dynamic raw,
  );

  @protected
  UpdateSeriesUserMetaDto dco_decode_update_series_user_meta_dto(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  SyncHandleDto
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncHandleDto(
    SseDeserializer deserializer,
  );

  @protected
  SyncHandleDto
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncHandleDto(
    SseDeserializer deserializer,
  );

  @protected
  SyncHandleDto
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncHandleDto(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<HomePageCountsDto>
  sse_decode_StreamSink_home_page_counts_dto_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<int> sse_decode_StreamSink_i_32_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<List<String>> sse_decode_StreamSink_list_String_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<List<HomeContinueReadingDto>>
  sse_decode_StreamSink_list_home_continue_reading_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<List<ReadingHistoryDto>>
  sse_decode_StreamSink_list_reading_history_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<List<SeriesComicOrderEntryDto>>
  sse_decode_StreamSink_list_series_comic_order_entry_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<List<SeriesDto>> sse_decode_StreamSink_list_series_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<SyncLibraryProgressDto>
  sse_decode_StreamSink_sync_library_progress_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<ThumbnailEventDto>
  sse_decode_StreamSink_thumbnail_event_dto_Sse(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AuthorPagedNamesDto sse_decode_author_paged_names_dto(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ComicDto sse_decode_box_autoadd_comic_dto(SseDeserializer deserializer);

  @protected
  ComicFilterDto sse_decode_box_autoadd_comic_filter_dto(
    SseDeserializer deserializer,
  );

  @protected
  ComicSortOptionDto sse_decode_box_autoadd_comic_sort_option_dto(
    SseDeserializer deserializer,
  );

  @protected
  ComicThumbnailDto sse_decode_box_autoadd_comic_thumbnail_dto(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  PageRequestDto sse_decode_box_autoadd_page_request_dto(
    SseDeserializer deserializer,
  );

  @protected
  ReadingHistoryDto sse_decode_box_autoadd_reading_history_dto(
    SseDeserializer deserializer,
  );

  @protected
  SeriesDto sse_decode_box_autoadd_series_dto(SseDeserializer deserializer);

  @protected
  SeriesFilterDto sse_decode_box_autoadd_series_filter_dto(
    SseDeserializer deserializer,
  );

  @protected
  SeriesReadingHistoryDto sse_decode_box_autoadd_series_reading_history_dto(
    SseDeserializer deserializer,
  );

  @protected
  SeriesSortOptionDto sse_decode_box_autoadd_series_sort_option_dto(
    SseDeserializer deserializer,
  );

  @protected
  UpdateComicUserMetaFrbDto
  sse_decode_box_autoadd_update_comic_user_meta_frb_dto(
    SseDeserializer deserializer,
  );

  @protected
  UpdateSeriesUserMetaDto sse_decode_box_autoadd_update_series_user_meta_dto(
    SseDeserializer deserializer,
  );

  @protected
  ComicDto sse_decode_comic_dto(SseDeserializer deserializer);

  @protected
  ComicFilterDto sse_decode_comic_filter_dto(SseDeserializer deserializer);

  @protected
  ComicSortOptionDto sse_decode_comic_sort_option_dto(
    SseDeserializer deserializer,
  );

  @protected
  ComicThumbnailDto sse_decode_comic_thumbnail_dto(
    SseDeserializer deserializer,
  );

  @protected
  HentaiErrorDto sse_decode_hentai_error_dto(SseDeserializer deserializer);

  @protected
  HomeContinueReadingDto sse_decode_home_continue_reading_dto(
    SseDeserializer deserializer,
  );

  @protected
  HomePageCountsDto sse_decode_home_page_counts_dto(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  LibrarySyncCountsDto sse_decode_library_sync_counts_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ComicDto> sse_decode_list_comic_dto(SseDeserializer deserializer);

  @protected
  List<HomeContinueReadingDto> sse_decode_list_home_continue_reading_dto(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ReadingHistoryDto> sse_decode_list_reading_history_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<SeriesComicOrderEntryDto> sse_decode_list_series_comic_order_entry_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<SeriesDto> sse_decode_list_series_dto(SseDeserializer deserializer);

  @protected
  List<SeriesItemDto> sse_decode_list_series_item_dto(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  ComicDto? sse_decode_opt_box_autoadd_comic_dto(SseDeserializer deserializer);

  @protected
  ComicThumbnailDto? sse_decode_opt_box_autoadd_comic_thumbnail_dto(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  ReadingHistoryDto? sse_decode_opt_box_autoadd_reading_history_dto(
    SseDeserializer deserializer,
  );

  @protected
  SeriesDto? sse_decode_opt_box_autoadd_series_dto(
    SseDeserializer deserializer,
  );

  @protected
  SeriesReadingHistoryDto?
  sse_decode_opt_box_autoadd_series_reading_history_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  PageRequestDto sse_decode_page_request_dto(SseDeserializer deserializer);

  @protected
  PagedComicResultDto sse_decode_paged_comic_result_dto(
    SseDeserializer deserializer,
  );

  @protected
  PagedReadingHistoryDto sse_decode_paged_reading_history_dto(
    SseDeserializer deserializer,
  );

  @protected
  PagedSeriesResultDto sse_decode_paged_series_result_dto(
    SseDeserializer deserializer,
  );

  @protected
  ReaderPageListDto sse_decode_reader_page_list_dto(
    SseDeserializer deserializer,
  );

  @protected
  ReadingHistoryDto sse_decode_reading_history_dto(
    SseDeserializer deserializer,
  );

  @protected
  SeriesComicOrderEntryDto sse_decode_series_comic_order_entry_dto(
    SseDeserializer deserializer,
  );

  @protected
  SeriesDto sse_decode_series_dto(SseDeserializer deserializer);

  @protected
  SeriesFilterDto sse_decode_series_filter_dto(SseDeserializer deserializer);

  @protected
  SeriesItemDto sse_decode_series_item_dto(SseDeserializer deserializer);

  @protected
  SeriesReadingHistoryDto sse_decode_series_reading_history_dto(
    SseDeserializer deserializer,
  );

  @protected
  SeriesSortOptionDto sse_decode_series_sort_option_dto(
    SseDeserializer deserializer,
  );

  @protected
  SyncLibraryPhaseDto sse_decode_sync_library_phase_dto(
    SseDeserializer deserializer,
  );

  @protected
  SyncLibraryProgressDto sse_decode_sync_library_progress_dto(
    SseDeserializer deserializer,
  );

  @protected
  SyncLibraryRouteDto sse_decode_sync_library_route_dto(
    SseDeserializer deserializer,
  );

  @protected
  TagPagedNamesDto sse_decode_tag_paged_names_dto(SseDeserializer deserializer);

  @protected
  ThumbnailEventDto sse_decode_thumbnail_event_dto(
    SseDeserializer deserializer,
  );

  @protected
  ThumbnailPriorityDto sse_decode_thumbnail_priority_dto(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UpdateComicUserMetaFrbDto sse_decode_update_comic_user_meta_frb_dto(
    SseDeserializer deserializer,
  );

  @protected
  UpdateSeriesUserMetaDto sse_decode_update_series_user_meta_dto(
    SseDeserializer deserializer,
  );

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncHandleDto(
    SyncHandleDto self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncHandleDto(
    SyncHandleDto self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncHandleDto(
    SyncHandleDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_home_page_counts_dto_Sse(
    RustStreamSink<HomePageCountsDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_i_32_Sse(
    RustStreamSink<int> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_list_String_Sse(
    RustStreamSink<List<String>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_list_home_continue_reading_dto_Sse(
    RustStreamSink<List<HomeContinueReadingDto>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_list_reading_history_dto_Sse(
    RustStreamSink<List<ReadingHistoryDto>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_list_series_comic_order_entry_dto_Sse(
    RustStreamSink<List<SeriesComicOrderEntryDto>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_list_series_dto_Sse(
    RustStreamSink<List<SeriesDto>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_sync_library_progress_dto_Sse(
    RustStreamSink<SyncLibraryProgressDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_thumbnail_event_dto_Sse(
    RustStreamSink<ThumbnailEventDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_author_paged_names_dto(
    AuthorPagedNamesDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_comic_dto(
    ComicDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_comic_filter_dto(
    ComicFilterDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_comic_sort_option_dto(
    ComicSortOptionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_comic_thumbnail_dto(
    ComicThumbnailDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_page_request_dto(
    PageRequestDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_reading_history_dto(
    ReadingHistoryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_series_dto(
    SeriesDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_series_filter_dto(
    SeriesFilterDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_series_reading_history_dto(
    SeriesReadingHistoryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_series_sort_option_dto(
    SeriesSortOptionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_update_comic_user_meta_frb_dto(
    UpdateComicUserMetaFrbDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_update_series_user_meta_dto(
    UpdateSeriesUserMetaDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_comic_dto(ComicDto self, SseSerializer serializer);

  @protected
  void sse_encode_comic_filter_dto(
    ComicFilterDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_comic_sort_option_dto(
    ComicSortOptionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_comic_thumbnail_dto(
    ComicThumbnailDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_hentai_error_dto(
    HentaiErrorDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_home_continue_reading_dto(
    HomeContinueReadingDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_home_page_counts_dto(
    HomePageCountsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_library_sync_counts_dto(
    LibrarySyncCountsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_comic_dto(List<ComicDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_home_continue_reading_dto(
    List<HomeContinueReadingDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_reading_history_dto(
    List<ReadingHistoryDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_series_comic_order_entry_dto(
    List<SeriesComicOrderEntryDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_series_dto(
    List<SeriesDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_series_item_dto(
    List<SeriesItemDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_comic_dto(
    ComicDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_comic_thumbnail_dto(
    ComicThumbnailDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_reading_history_dto(
    ReadingHistoryDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_series_dto(
    SeriesDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_series_reading_history_dto(
    SeriesReadingHistoryDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_page_request_dto(
    PageRequestDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_paged_comic_result_dto(
    PagedComicResultDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_paged_reading_history_dto(
    PagedReadingHistoryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_paged_series_result_dto(
    PagedSeriesResultDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_reader_page_list_dto(
    ReaderPageListDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_reading_history_dto(
    ReadingHistoryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_series_comic_order_entry_dto(
    SeriesComicOrderEntryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_series_dto(SeriesDto self, SseSerializer serializer);

  @protected
  void sse_encode_series_filter_dto(
    SeriesFilterDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_series_item_dto(SeriesItemDto self, SseSerializer serializer);

  @protected
  void sse_encode_series_reading_history_dto(
    SeriesReadingHistoryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_series_sort_option_dto(
    SeriesSortOptionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sync_library_phase_dto(
    SyncLibraryPhaseDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sync_library_progress_dto(
    SyncLibraryProgressDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sync_library_route_dto(
    SyncLibraryRouteDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_tag_paged_names_dto(
    TagPagedNamesDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_thumbnail_event_dto(
    ThumbnailEventDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_thumbnail_priority_dto(
    ThumbnailPriorityDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_update_comic_user_meta_frb_dto(
    UpdateComicUserMetaFrbDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_update_series_user_meta_dto(
    UpdateSeriesUserMetaDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncHandleDto(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncHandleDto(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncHandleDto(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncHandleDto(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncHandleDto(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncHandleDto(
    int ptr,
  );
}
