// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'comic.dart';
import 'init.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

List<String> listAllAuthorsFrb() =>
    RustLib.instance.api.crateApiAuthorListAllAuthorsFrb();

AuthorPagedNamesDto fetchAuthorsPageFrb({required PageRequestDto request}) =>
    RustLib.instance.api.crateApiAuthorFetchAuthorsPageFrb(request: request);

void addAuthorFrb({required String name}) =>
    RustLib.instance.api.crateApiAuthorAddAuthorFrb(name: name);

void deleteAuthorsByNamesFrb({required List<String> names}) =>
    RustLib.instance.api.crateApiAuthorDeleteAuthorsByNamesFrb(names: names);

void renameAuthorFrb({required String oldName, required String newName}) =>
    RustLib.instance.api.crateApiAuthorRenameAuthorFrb(
      oldName: oldName,
      newName: newName,
    );

Stream<List<String>> watchAuthorsFrb() =>
    RustLib.instance.api.crateApiAuthorWatchAuthorsFrb();

class AuthorPagedNamesDto {
  final List<String> items;
  final PlatformInt64 totalCount;
  final int page;
  final int pageSize;

  const AuthorPagedNamesDto({
    required this.items,
    required this.totalCount,
    required this.page,
    required this.pageSize,
  });

  @override
  int get hashCode =>
      items.hashCode ^ totalCount.hashCode ^ page.hashCode ^ pageSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuthorPagedNamesDto &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          totalCount == other.totalCount &&
          page == other.page &&
          pageSize == other.pageSize;
}
