// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'init.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`

void initDbFrb({required String appDataDir, required String dbFileName}) =>
    RustLib.instance.api.crateApiComicInitDbFrb(
      appDataDir: appDataDir,
      dbFileName: dbFileName,
    );

String comicIdFromPathFrb({required String rawPath}) =>
    RustLib.instance.api.crateApiComicComicIdFromPathFrb(rawPath: rawPath);

PagedComicResultDto fetchComicsPageFrb({
  required PageRequestDto request,
  required ComicFilterDto filter,
  required ComicSortOptionDto sort,
}) => RustLib.instance.api.crateApiComicFetchComicsPageFrb(
  request: request,
  filter: filter,
  sort: sort,
);

ComicDto? findComicByIdFrb({required String comicId}) =>
    RustLib.instance.api.crateApiComicFindComicByIdFrb(comicId: comicId);

List<ComicDto> searchByKeywordFrb({required String keyword}) =>
    RustLib.instance.api.crateApiComicSearchByKeywordFrb(keyword: keyword);

PlatformInt64 countAllComicsFrb() =>
    RustLib.instance.api.crateApiComicCountAllComicsFrb();

Stream<int> watchComicChanges() =>
    RustLib.instance.api.crateApiComicWatchComicChanges();

class ComicDto {
  final String comicId;
  final String path;
  final String resourceType;
  final String title;
  final String contentRating;
  final int? pageCount;
  final List<String> authors;
  final List<String> tags;

  const ComicDto({
    required this.comicId,
    required this.path,
    required this.resourceType,
    required this.title,
    required this.contentRating,
    this.pageCount,
    required this.authors,
    required this.tags,
  });

  @override
  int get hashCode =>
      comicId.hashCode ^
      path.hashCode ^
      resourceType.hashCode ^
      title.hashCode ^
      contentRating.hashCode ^
      pageCount.hashCode ^
      authors.hashCode ^
      tags.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ComicDto &&
          runtimeType == other.runtimeType &&
          comicId == other.comicId &&
          path == other.path &&
          resourceType == other.resourceType &&
          title == other.title &&
          contentRating == other.contentRating &&
          pageCount == other.pageCount &&
          authors == other.authors &&
          tags == other.tags;
}

class ComicFilterDto {
  final bool showR18;
  final String? query;
  final List<String> resourceTypes;
  final List<String> contentRatings;
  final List<String> tagsAll;
  final List<String> tagsAny;
  final List<String> tagsExclude;
  final bool excludeComicsInAnySeries;

  const ComicFilterDto({
    required this.showR18,
    this.query,
    required this.resourceTypes,
    required this.contentRatings,
    required this.tagsAll,
    required this.tagsAny,
    required this.tagsExclude,
    required this.excludeComicsInAnySeries,
  });

  @override
  int get hashCode =>
      showR18.hashCode ^
      query.hashCode ^
      resourceTypes.hashCode ^
      contentRatings.hashCode ^
      tagsAll.hashCode ^
      tagsAny.hashCode ^
      tagsExclude.hashCode ^
      excludeComicsInAnySeries.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ComicFilterDto &&
          runtimeType == other.runtimeType &&
          showR18 == other.showR18 &&
          query == other.query &&
          resourceTypes == other.resourceTypes &&
          contentRatings == other.contentRatings &&
          tagsAll == other.tagsAll &&
          tagsAny == other.tagsAny &&
          tagsExclude == other.tagsExclude &&
          excludeComicsInAnySeries == other.excludeComicsInAnySeries;
}

class ComicSortOptionDto {
  final bool descending;

  const ComicSortOptionDto({required this.descending});

  @override
  int get hashCode => descending.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ComicSortOptionDto &&
          runtimeType == other.runtimeType &&
          descending == other.descending;
}

class PageRequestDto {
  final int page;
  final int pageSize;

  const PageRequestDto({required this.page, required this.pageSize});

  @override
  int get hashCode => page.hashCode ^ pageSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PageRequestDto &&
          runtimeType == other.runtimeType &&
          page == other.page &&
          pageSize == other.pageSize;
}

class PagedComicResultDto {
  final List<ComicDto> items;
  final PlatformInt64 totalCount;
  final int page;
  final int pageSize;

  const PagedComicResultDto({
    required this.items,
    required this.totalCount,
    required this.page,
    required this.pageSize,
  });

  @override
  int get hashCode =>
      items.hashCode ^ totalCount.hashCode ^ page.hashCode ^ pageSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PagedComicResultDto &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          totalCount == other.totalCount &&
          page == other.page &&
          pageSize == other.pageSize;
}
