// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'init.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`

void initDbFrb({required String appDataDir, required String dbFileName}) =>
    RustLib.instance.api.crateApiComicInitDbFrb(
      appDataDir: appDataDir,
      dbFileName: dbFileName,
    );

String comicIdFromPathFrb({required String rawPath}) =>
    RustLib.instance.api.crateApiComicComicIdFromPathFrb(rawPath: rawPath);

PagedComicResultDto fetchComicsPageFrb({
  required PageRequestDto request,
  required ComicFilterDto filter,
  required ComicSortOptionDto sort,
}) => RustLib.instance.api.crateApiComicFetchComicsPageFrb(
  request: request,
  filter: filter,
  sort: sort,
);

ComicDto? findComicByIdFrb({required String comicId}) =>
    RustLib.instance.api.crateApiComicFindComicByIdFrb(comicId: comicId);

List<ComicDto> searchByKeywordFrb({required String keyword}) =>
    RustLib.instance.api.crateApiComicSearchByKeywordFrb(keyword: keyword);

void deleteComicsByIdsFrb({required List<String> comicIds}) =>
    RustLib.instance.api.crateApiComicDeleteComicsByIdsFrb(comicIds: comicIds);

void updateComicUserMetaFrb({
  required String comicId,
  required UpdateComicUserMetaFrbDto meta,
}) => RustLib.instance.api.crateApiComicUpdateComicUserMetaFrb(
  comicId: comicId,
  meta: meta,
);

void setComicMetaLocksFrb({
  required String comicId,
  required SetComicMetaLocksFrbDto locks,
}) => RustLib.instance.api.crateApiComicSetComicMetaLocksFrb(
  comicId: comicId,
  locks: locks,
);

Future<void> refreshComicMetadataFrb({required String comicId}) =>
    RustLib.instance.api.crateApiComicRefreshComicMetadataFrb(comicId: comicId);

List<ComicDto> searchByTagExpressionFrb({
  required List<String> mustInclude,
  required List<String> optionalOr,
  required List<String> mustExclude,
}) => RustLib.instance.api.crateApiComicSearchByTagExpressionFrb(
  mustInclude: mustInclude,
  optionalOr: optionalOr,
  mustExclude: mustExclude,
);

PlatformInt64 countAllComicsFrb() =>
    RustLib.instance.api.crateApiComicCountAllComicsFrb();

Stream<int> watchComicChanges() =>
    RustLib.instance.api.crateApiComicWatchComicChanges();

class ComicDto {
  final String comicId;
  final String path;
  final String resourceType;
  final PlatformInt64 resourceSize;
  final PlatformInt64 createdAt;
  final PlatformInt64 lastUpdatedAt;
  final String title;
  final String contentRating;
  final int pageCount;
  final String? description;
  final PlatformInt64? publishedAt;
  final PlatformInt64? lastReadTimeMs;
  final List<String> authors;
  final List<String> tags;
  final List<String> languages;
  final ComicMetaLocksDto locks;
  final String libraryId;

  const ComicDto({
    required this.comicId,
    required this.path,
    required this.resourceType,
    required this.resourceSize,
    required this.createdAt,
    required this.lastUpdatedAt,
    required this.title,
    required this.contentRating,
    required this.pageCount,
    this.description,
    this.publishedAt,
    this.lastReadTimeMs,
    required this.authors,
    required this.tags,
    required this.languages,
    required this.locks,
    required this.libraryId,
  });

  @override
  int get hashCode =>
      comicId.hashCode ^
      path.hashCode ^
      resourceType.hashCode ^
      resourceSize.hashCode ^
      createdAt.hashCode ^
      lastUpdatedAt.hashCode ^
      title.hashCode ^
      contentRating.hashCode ^
      pageCount.hashCode ^
      description.hashCode ^
      publishedAt.hashCode ^
      lastReadTimeMs.hashCode ^
      authors.hashCode ^
      tags.hashCode ^
      languages.hashCode ^
      locks.hashCode ^
      libraryId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ComicDto &&
          runtimeType == other.runtimeType &&
          comicId == other.comicId &&
          path == other.path &&
          resourceType == other.resourceType &&
          resourceSize == other.resourceSize &&
          createdAt == other.createdAt &&
          lastUpdatedAt == other.lastUpdatedAt &&
          title == other.title &&
          contentRating == other.contentRating &&
          pageCount == other.pageCount &&
          description == other.description &&
          publishedAt == other.publishedAt &&
          lastReadTimeMs == other.lastReadTimeMs &&
          authors == other.authors &&
          tags == other.tags &&
          languages == other.languages &&
          locks == other.locks &&
          libraryId == other.libraryId;
}

class ComicFilterDto {
  final bool showR18;
  final String? query;
  final List<String> resourceTypes;
  final List<String> contentRatings;
  final List<String> tagsAll;
  final List<String> tagsAny;
  final List<String> tagsExclude;
  final List<String> authorsAll;
  final List<String> authorsAny;
  final List<String> authorsExclude;
  final String? libraryId;

  const ComicFilterDto({
    required this.showR18,
    this.query,
    required this.resourceTypes,
    required this.contentRatings,
    required this.tagsAll,
    required this.tagsAny,
    required this.tagsExclude,
    required this.authorsAll,
    required this.authorsAny,
    required this.authorsExclude,
    this.libraryId,
  });

  @override
  int get hashCode =>
      showR18.hashCode ^
      query.hashCode ^
      resourceTypes.hashCode ^
      contentRatings.hashCode ^
      tagsAll.hashCode ^
      tagsAny.hashCode ^
      tagsExclude.hashCode ^
      authorsAll.hashCode ^
      authorsAny.hashCode ^
      authorsExclude.hashCode ^
      libraryId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ComicFilterDto &&
          runtimeType == other.runtimeType &&
          showR18 == other.showR18 &&
          query == other.query &&
          resourceTypes == other.resourceTypes &&
          contentRatings == other.contentRatings &&
          tagsAll == other.tagsAll &&
          tagsAny == other.tagsAny &&
          tagsExclude == other.tagsExclude &&
          authorsAll == other.authorsAll &&
          authorsAny == other.authorsAny &&
          authorsExclude == other.authorsExclude &&
          libraryId == other.libraryId;
}

class ComicMetaLocksDto {
  final bool title;
  final bool description;
  final bool publishedAt;
  final bool contentRating;
  final bool authors;
  final bool tags;
  final bool languages;

  const ComicMetaLocksDto({
    required this.title,
    required this.description,
    required this.publishedAt,
    required this.contentRating,
    required this.authors,
    required this.tags,
    required this.languages,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      description.hashCode ^
      publishedAt.hashCode ^
      contentRating.hashCode ^
      authors.hashCode ^
      tags.hashCode ^
      languages.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ComicMetaLocksDto &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          description == other.description &&
          publishedAt == other.publishedAt &&
          contentRating == other.contentRating &&
          authors == other.authors &&
          tags == other.tags &&
          languages == other.languages;
}

enum ComicSortFieldDto {
  title,
  createdAt,
  lastUpdatedAt,
  publishedAt,
  readAt,
  fileSize,
  pageCount;

  static Future<ComicSortFieldDto> default_() =>
      RustLib.instance.api.crateApiComicComicSortFieldDtoDefault();
}

class ComicSortOptionDto {
  final ComicSortFieldDto field;
  final bool descending;

  const ComicSortOptionDto({required this.field, required this.descending});

  @override
  int get hashCode => field.hashCode ^ descending.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ComicSortOptionDto &&
          runtimeType == other.runtimeType &&
          field == other.field &&
          descending == other.descending;
}

class PageRequestDto {
  final int page;
  final int pageSize;

  const PageRequestDto({required this.page, required this.pageSize});

  @override
  int get hashCode => page.hashCode ^ pageSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PageRequestDto &&
          runtimeType == other.runtimeType &&
          page == other.page &&
          pageSize == other.pageSize;
}

class PagedComicResultDto {
  final List<ComicDto> items;
  final PlatformInt64 totalCount;
  final int page;
  final int pageSize;

  const PagedComicResultDto({
    required this.items,
    required this.totalCount,
    required this.page,
    required this.pageSize,
  });

  @override
  int get hashCode =>
      items.hashCode ^ totalCount.hashCode ^ page.hashCode ^ pageSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PagedComicResultDto &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          totalCount == other.totalCount &&
          page == other.page &&
          pageSize == other.pageSize;
}

class SetComicMetaLocksFrbDto {
  final bool? title;
  final bool? description;
  final bool? publishedAt;
  final bool? contentRating;
  final bool? authors;
  final bool? tags;
  final bool? languages;

  const SetComicMetaLocksFrbDto({
    this.title,
    this.description,
    this.publishedAt,
    this.contentRating,
    this.authors,
    this.tags,
    this.languages,
  });

  static Future<SetComicMetaLocksFrbDto> default_() =>
      RustLib.instance.api.crateApiComicSetComicMetaLocksFrbDtoDefault();

  @override
  int get hashCode =>
      title.hashCode ^
      description.hashCode ^
      publishedAt.hashCode ^
      contentRating.hashCode ^
      authors.hashCode ^
      tags.hashCode ^
      languages.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SetComicMetaLocksFrbDto &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          description == other.description &&
          publishedAt == other.publishedAt &&
          contentRating == other.contentRating &&
          authors == other.authors &&
          tags == other.tags &&
          languages == other.languages;
}

class UpdateComicUserMetaFrbDto {
  final String? title;
  final String? contentRating;
  final String? description;
  final PlatformInt64? publishedAt;
  final List<String>? authors;
  final List<String>? tags;
  final List<String>? languages;

  const UpdateComicUserMetaFrbDto({
    this.title,
    this.contentRating,
    this.description,
    this.publishedAt,
    this.authors,
    this.tags,
    this.languages,
  });

  static Future<UpdateComicUserMetaFrbDto> default_() =>
      RustLib.instance.api.crateApiComicUpdateComicUserMetaFrbDtoDefault();

  @override
  int get hashCode =>
      title.hashCode ^
      contentRating.hashCode ^
      description.hashCode ^
      publishedAt.hashCode ^
      authors.hashCode ^
      tags.hashCode ^
      languages.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateComicUserMetaFrbDto &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          contentRating == other.contentRating &&
          description == other.description &&
          publishedAt == other.publishedAt &&
          authors == other.authors &&
          tags == other.tags &&
          languages == other.languages;
}
