// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'init.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`, `from`, `from`, `from`

void recordReadingFrb({required ReadingHistoryDto history}) =>
    RustLib.instance.api.crateApiHistoryRecordReadingFrb(history: history);

ReadingHistoryDto? getReadingByComicIdFrb({required String comicId}) => RustLib
    .instance
    .api
    .crateApiHistoryGetReadingByComicIdFrb(comicId: comicId);

PagedReadingHistoryDto fetchReadingPageFrb({
  required int page,
  required int pageSize,
}) => RustLib.instance.api.crateApiHistoryFetchReadingPageFrb(
  page: page,
  pageSize: pageSize,
);

int deleteReadingByComicIdFrb({required String comicId}) => RustLib.instance.api
    .crateApiHistoryDeleteReadingByComicIdFrb(comicId: comicId);

int deleteReadingByComicIdsFrb({required List<String> comicIds}) => RustLib
    .instance
    .api
    .crateApiHistoryDeleteReadingByComicIdsFrb(comicIds: comicIds);

int clearAllReadingFrb() =>
    RustLib.instance.api.crateApiHistoryClearAllReadingFrb();

Stream<List<ReadingHistoryDto>> watchReadingHistoriesFrb() =>
    RustLib.instance.api.crateApiHistoryWatchReadingHistoriesFrb();

class PagedReadingHistoryDto {
  final List<ReadingHistoryDto> items;
  final PlatformInt64 totalCount;

  const PagedReadingHistoryDto({required this.items, required this.totalCount});

  @override
  int get hashCode => items.hashCode ^ totalCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PagedReadingHistoryDto &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          totalCount == other.totalCount;
}

class ReadingHistoryDto {
  final String comicId;
  final String title;
  final PlatformInt64 lastReadTimeMs;
  final int? pageIndex;

  const ReadingHistoryDto({
    required this.comicId,
    required this.title,
    required this.lastReadTimeMs,
    this.pageIndex,
  });

  @override
  int get hashCode =>
      comicId.hashCode ^
      title.hashCode ^
      lastReadTimeMs.hashCode ^
      pageIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReadingHistoryDto &&
          runtimeType == other.runtimeType &&
          comicId == other.comicId &&
          title == other.title &&
          lastReadTimeMs == other.lastReadTimeMs &&
          pageIndex == other.pageIndex;
}
