// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'init.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`

Stream<HomePageCountsDto> watchHomePageCountsFrb({required bool excludeR18}) =>
    RustLib.instance.api.crateApiHomeWatchHomePageCountsFrb(
      excludeR18: excludeR18,
    );

Stream<List<HomeContinueReadingDto>> watchContinueReadingTop5Frb({
  required bool excludeR18,
}) => RustLib.instance.api.crateApiHomeWatchContinueReadingTop5Frb(
  excludeR18: excludeR18,
);

Stream<List<HomeLibraryAlertDto>> watchHomeLibraryAlertsFrb() =>
    RustLib.instance.api.crateApiHomeWatchHomeLibraryAlertsFrb();

Stream<List<HomeRecentlyAddedDto>> watchRecentlyAddedOnHomeFrb({
  required bool excludeR18,
}) => RustLib.instance.api.crateApiHomeWatchRecentlyAddedOnHomeFrb(
  excludeR18: excludeR18,
);

class HomeContinueReadingDto {
  final String comicId;
  final String title;
  final PlatformInt64 lastReadTimeMs;
  final int? pageIndex;

  const HomeContinueReadingDto({
    required this.comicId,
    required this.title,
    required this.lastReadTimeMs,
    this.pageIndex,
  });

  @override
  int get hashCode =>
      comicId.hashCode ^
      title.hashCode ^
      lastReadTimeMs.hashCode ^
      pageIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HomeContinueReadingDto &&
          runtimeType == other.runtimeType &&
          comicId == other.comicId &&
          title == other.title &&
          lastReadTimeMs == other.lastReadTimeMs &&
          pageIndex == other.pageIndex;
}

class HomeLibraryAlertDto {
  final String libraryId;
  final String displayName;
  final HomeLibraryAlertKindDto kind;
  final PlatformInt64? lastSuccessAtMs;
  final String? lastErrorMessage;
  final int? staleDays;
  final int? pendingResourceCount;

  const HomeLibraryAlertDto({
    required this.libraryId,
    required this.displayName,
    required this.kind,
    this.lastSuccessAtMs,
    this.lastErrorMessage,
    this.staleDays,
    this.pendingResourceCount,
  });

  @override
  int get hashCode =>
      libraryId.hashCode ^
      displayName.hashCode ^
      kind.hashCode ^
      lastSuccessAtMs.hashCode ^
      lastErrorMessage.hashCode ^
      staleDays.hashCode ^
      pendingResourceCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HomeLibraryAlertDto &&
          runtimeType == other.runtimeType &&
          libraryId == other.libraryId &&
          displayName == other.displayName &&
          kind == other.kind &&
          lastSuccessAtMs == other.lastSuccessAtMs &&
          lastErrorMessage == other.lastErrorMessage &&
          staleDays == other.staleDays &&
          pendingResourceCount == other.pendingResourceCount;
}

enum HomeLibraryAlertKindDto {
  remoteUnreachable,
  syncFailed,
  staleSync,
  pendingResourcesDetected,
}

class HomePageCountsDto {
  final int comicCount;
  final int tagCount;
  final int seriesCount;
  final int authorCount;
  final int libraryCount;

  const HomePageCountsDto({
    required this.comicCount,
    required this.tagCount,
    required this.seriesCount,
    required this.authorCount,
    required this.libraryCount,
  });

  @override
  int get hashCode =>
      comicCount.hashCode ^
      tagCount.hashCode ^
      seriesCount.hashCode ^
      authorCount.hashCode ^
      libraryCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HomePageCountsDto &&
          runtimeType == other.runtimeType &&
          comicCount == other.comicCount &&
          tagCount == other.tagCount &&
          seriesCount == other.seriesCount &&
          authorCount == other.authorCount &&
          libraryCount == other.libraryCount;
}

class HomeRecentlyAddedDto {
  final String comicId;
  final String title;
  final String libraryId;
  final String libraryDisplayName;
  final PlatformInt64 createdAtMs;

  const HomeRecentlyAddedDto({
    required this.comicId,
    required this.title,
    required this.libraryId,
    required this.libraryDisplayName,
    required this.createdAtMs,
  });

  @override
  int get hashCode =>
      comicId.hashCode ^
      title.hashCode ^
      libraryId.hashCode ^
      libraryDisplayName.hashCode ^
      createdAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HomeRecentlyAddedDto &&
          runtimeType == other.runtimeType &&
          comicId == other.comicId &&
          title == other.title &&
          libraryId == other.libraryId &&
          libraryDisplayName == other.libraryDisplayName &&
          createdAtMs == other.createdAtMs;
}
