// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'init.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

HomePageCountsDto getHomePageCountsFrb({required bool excludeR18}) => RustLib
    .instance
    .api
    .crateApiHomeGetHomePageCountsFrb(excludeR18: excludeR18);

Stream<HomePageCountsDto> watchHomePageCountsFrb({required bool excludeR18}) =>
    RustLib.instance.api.crateApiHomeWatchHomePageCountsFrb(
      excludeR18: excludeR18,
    );

class HomePageCountsDto {
  final int comicCount;
  final int tagCount;
  final int seriesCount;
  final int readingRecordCount;

  const HomePageCountsDto({
    required this.comicCount,
    required this.tagCount,
    required this.seriesCount,
    required this.readingRecordCount,
  });

  @override
  int get hashCode =>
      comicCount.hashCode ^
      tagCount.hashCode ^
      seriesCount.hashCode ^
      readingRecordCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HomePageCountsDto &&
          runtimeType == other.runtimeType &&
          comicCount == other.comicCount &&
          tagCount == other.tagCount &&
          seriesCount == other.seriesCount &&
          readingRecordCount == other.readingRecordCount;
}
