// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

void initDbFrb({required String appDataDir, required String dbFileName}) =>
    RustLib.instance.api.crateApiInitInitDbFrb(
      appDataDir: appDataDir,
      dbFileName: dbFileName,
    );

String comicIdFromPathFrb({required String rawPath}) =>
    RustLib.instance.api.crateApiInitComicIdFromPathFrb(rawPath: rawPath);

class HentaiErrorDto implements FrbException {
  final String code;
  final String message;
  final String? context;

  const HentaiErrorDto({
    required this.code,
    required this.message,
    this.context,
  });

  @override
  int get hashCode => code.hashCode ^ message.hashCode ^ context.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HentaiErrorDto &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message &&
          context == other.context;
}
