// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'init.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'sync.dart';

// These functions are ignored because they are not marked as `pub`: `map_format_group_core`, `map_format_group`, `map_scan_interval_core`, `map_scan_interval`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `from`

List<LibraryDto> listLibrariesFrb() =>
    RustLib.instance.api.crateApiLibraryListLibrariesFrb();

LibraryDto createLocalLibraryFrb({required String rootPath, String? name}) =>
    RustLib.instance.api.crateApiLibraryCreateLocalLibraryFrb(
      rootPath: rootPath,
      name: name,
    );

LibraryDto createRemoteLibraryFrb({
  required String rootUrl,
  required String username,
  required bool allowHttp,
  String? name,
}) => RustLib.instance.api.crateApiLibraryCreateRemoteLibraryFrb(
  rootUrl: rootUrl,
  username: username,
  allowHttp: allowHttp,
  name: name,
);

LibraryDto updateRemoteLibraryFrb({
  required String libraryId,
  required String rootUrl,
  required String username,
  required bool allowHttp,
}) => RustLib.instance.api.crateApiLibraryUpdateRemoteLibraryFrb(
  libraryId: libraryId,
  rootUrl: rootUrl,
  username: username,
  allowHttp: allowHttp,
);

LibraryDto updateLocalLibraryRootFrb({
  required String libraryId,
  required String rootPath,
}) => RustLib.instance.api.crateApiLibraryUpdateLocalLibraryRootFrb(
  libraryId: libraryId,
  rootPath: rootPath,
);

void deleteLibraryFrb({required String libraryId}) =>
    RustLib.instance.api.crateApiLibraryDeleteLibraryFrb(libraryId: libraryId);

String? getCurrentLibraryIdFrb() =>
    RustLib.instance.api.crateApiLibraryGetCurrentLibraryIdFrb();

void setCurrentLibraryIdFrb({String? libraryId}) => RustLib.instance.api
    .crateApiLibrarySetCurrentLibraryIdFrb(libraryId: libraryId);

LibraryDto updateLibraryFormatGroupsFrb({
  required String libraryId,
  required List<FormatGroupDto> groups,
}) => RustLib.instance.api.crateApiLibraryUpdateLibraryFormatGroupsFrb(
  libraryId: libraryId,
  groups: groups,
);

LibraryDto updateLibrarySettingsFrb({
  required String libraryId,
  required String name,
  required List<FormatGroupDto> groups,
  required bool scanOnStartup,
  required ScanIntervalDto scanInterval,
}) => RustLib.instance.api.crateApiLibraryUpdateLibrarySettingsFrb(
  libraryId: libraryId,
  name: name,
  groups: groups,
  scanOnStartup: scanOnStartup,
  scanInterval: scanInterval,
);

void setAllLibrariesScanOnStartupFrb({required bool enabled}) => RustLib
    .instance
    .api
    .crateApiLibrarySetAllLibrariesScanOnStartupFrb(enabled: enabled);

class LibraryDto {
  final String libraryId;
  final String kind;
  final String rootPath;
  final String name;
  final List<FormatGroupDto> enabledFormatGroups;
  final PlatformInt64 createdAt;
  final String username;
  final bool allowHttp;
  final bool scanOnStartup;
  final ScanIntervalDto scanInterval;

  const LibraryDto({
    required this.libraryId,
    required this.kind,
    required this.rootPath,
    required this.name,
    required this.enabledFormatGroups,
    required this.createdAt,
    required this.username,
    required this.allowHttp,
    required this.scanOnStartup,
    required this.scanInterval,
  });

  @override
  int get hashCode =>
      libraryId.hashCode ^
      kind.hashCode ^
      rootPath.hashCode ^
      name.hashCode ^
      enabledFormatGroups.hashCode ^
      createdAt.hashCode ^
      username.hashCode ^
      allowHttp.hashCode ^
      scanOnStartup.hashCode ^
      scanInterval.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LibraryDto &&
          runtimeType == other.runtimeType &&
          libraryId == other.libraryId &&
          kind == other.kind &&
          rootPath == other.rootPath &&
          name == other.name &&
          enabledFormatGroups == other.enabledFormatGroups &&
          createdAt == other.createdAt &&
          username == other.username &&
          allowHttp == other.allowHttp &&
          scanOnStartup == other.scanOnStartup &&
          scanInterval == other.scanInterval;
}

enum ScanIntervalDto {
  disabled,
  hourly,
  every6Hours,
  every12Hours,
  daily,
  weekly,
}
