// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'init.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'sync.dart';

// These functions are ignored because they are not marked as `pub`: `map_format_group_core`, `map_format_group`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

List<LibraryDto> listLibrariesFrb() =>
    RustLib.instance.api.crateApiLibraryListLibrariesFrb();

LibraryDto createLocalLibraryFrb({required String rootPath}) => RustLib
    .instance
    .api
    .crateApiLibraryCreateLocalLibraryFrb(rootPath: rootPath);

void deleteLibraryFrb({required String libraryId}) =>
    RustLib.instance.api.crateApiLibraryDeleteLibraryFrb(libraryId: libraryId);

String? getCurrentLibraryIdFrb() =>
    RustLib.instance.api.crateApiLibraryGetCurrentLibraryIdFrb();

void setCurrentLibraryIdFrb({String? libraryId}) => RustLib.instance.api
    .crateApiLibrarySetCurrentLibraryIdFrb(libraryId: libraryId);

LibraryDto updateLibraryFormatGroupsFrb({
  required String libraryId,
  required List<FormatGroupDto> groups,
}) => RustLib.instance.api.crateApiLibraryUpdateLibraryFormatGroupsFrb(
  libraryId: libraryId,
  groups: groups,
);

class LibraryDto {
  final String libraryId;
  final String kind;
  final String rootPath;
  final String name;
  final List<FormatGroupDto> enabledFormatGroups;
  final PlatformInt64 createdAt;

  const LibraryDto({
    required this.libraryId,
    required this.kind,
    required this.rootPath,
    required this.name,
    required this.enabledFormatGroups,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      libraryId.hashCode ^
      kind.hashCode ^
      rootPath.hashCode ^
      name.hashCode ^
      enabledFormatGroups.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LibraryDto &&
          runtimeType == other.runtimeType &&
          libraryId == other.libraryId &&
          kind == other.kind &&
          rootPath == other.rootPath &&
          name == other.name &&
          enabledFormatGroups == other.enabledFormatGroups &&
          createdAt == other.createdAt;
}
