// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'init.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

void configureRustLogFrb({required String appDataDir}) => RustLib.instance.api
    .crateApiLoggingConfigureRustLogFrb(appDataDir: appDataDir);

void setDiagnosticLoggingFrb({required bool verbose}) => RustLib.instance.api
    .crateApiLoggingSetDiagnosticLoggingFrb(verbose: verbose);
