// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'init.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

Uint8List exportComicMetadataFrb({
  required ExportComicMetadataOptionsDto options,
}) => RustLib.instance.api.crateApiMetadataBackupExportComicMetadataFrb(
  options: options,
);

MetadataBackupManifestDto peekMetadataBackupManifestFrb({
  required List<int> bytes,
}) => RustLib.instance.api.crateApiMetadataBackupPeekMetadataBackupManifestFrb(
  bytes: bytes,
);

PreviewImportComicMetadataResultDto previewImportComicMetadataFrb({
  required List<int> bytes,
}) => RustLib.instance.api.crateApiMetadataBackupPreviewImportComicMetadataFrb(
  bytes: bytes,
);

ImportComicMetadataResultDto importComicMetadataFrb({
  required List<int> bytes,
}) => RustLib.instance.api.crateApiMetadataBackupImportComicMetadataFrb(
  bytes: bytes,
);

class AmbiguousSampleDto {
  final String comicId;
  final String path;
  final String title;
  final List<String> candidateComicIds;

  const AmbiguousSampleDto({
    required this.comicId,
    required this.path,
    required this.title,
    required this.candidateComicIds,
  });

  @override
  int get hashCode =>
      comicId.hashCode ^
      path.hashCode ^
      title.hashCode ^
      candidateComicIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AmbiguousSampleDto &&
          runtimeType == other.runtimeType &&
          comicId == other.comicId &&
          path == other.path &&
          title == other.title &&
          candidateComicIds == other.candidateComicIds;
}

class ExportComicMetadataOptionsDto {
  final String? libraryId;
  final bool includeOrphanFacets;

  const ExportComicMetadataOptionsDto({
    this.libraryId,
    required this.includeOrphanFacets,
  });

  @override
  int get hashCode => libraryId.hashCode ^ includeOrphanFacets.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExportComicMetadataOptionsDto &&
          runtimeType == other.runtimeType &&
          libraryId == other.libraryId &&
          includeOrphanFacets == other.includeOrphanFacets;
}

class ImportComicMetadataResultDto {
  final int applied;
  final int skippedNotFound;
  final int skippedAmbiguous;
  final List<String> errors;

  const ImportComicMetadataResultDto({
    required this.applied,
    required this.skippedNotFound,
    required this.skippedAmbiguous,
    required this.errors,
  });

  @override
  int get hashCode =>
      applied.hashCode ^
      skippedNotFound.hashCode ^
      skippedAmbiguous.hashCode ^
      errors.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportComicMetadataResultDto &&
          runtimeType == other.runtimeType &&
          applied == other.applied &&
          skippedNotFound == other.skippedNotFound &&
          skippedAmbiguous == other.skippedAmbiguous &&
          errors == other.errors;
}

enum MatchTierDto { path, libraryRelative }

class MetadataBackupManifestDto {
  final int schemaVersion;
  final String exportedAt;
  final String appVersion;
  final int comicCount;
  final bool includeOrphanFacets;
  final String? libraryId;

  const MetadataBackupManifestDto({
    required this.schemaVersion,
    required this.exportedAt,
    required this.appVersion,
    required this.comicCount,
    required this.includeOrphanFacets,
    this.libraryId,
  });

  @override
  int get hashCode =>
      schemaVersion.hashCode ^
      exportedAt.hashCode ^
      appVersion.hashCode ^
      comicCount.hashCode ^
      includeOrphanFacets.hashCode ^
      libraryId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MetadataBackupManifestDto &&
          runtimeType == other.runtimeType &&
          schemaVersion == other.schemaVersion &&
          exportedAt == other.exportedAt &&
          appVersion == other.appVersion &&
          comicCount == other.comicCount &&
          includeOrphanFacets == other.includeOrphanFacets &&
          libraryId == other.libraryId;
}

class NotFoundSampleDto {
  final String comicId;
  final String path;
  final String title;

  const NotFoundSampleDto({
    required this.comicId,
    required this.path,
    required this.title,
  });

  @override
  int get hashCode => comicId.hashCode ^ path.hashCode ^ title.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NotFoundSampleDto &&
          runtimeType == other.runtimeType &&
          comicId == other.comicId &&
          path == other.path &&
          title == other.title;
}

class PreviewImportComicMetadataResultDto {
  final int wouldApply;
  final int skippedNotFound;
  final int skippedAmbiguous;
  final int wouldUpsertOrphanFacetCount;
  final List<WouldApplySampleDto> samplesWouldApply;
  final List<NotFoundSampleDto> samplesNotFound;
  final List<AmbiguousSampleDto> samplesAmbiguous;

  const PreviewImportComicMetadataResultDto({
    required this.wouldApply,
    required this.skippedNotFound,
    required this.skippedAmbiguous,
    required this.wouldUpsertOrphanFacetCount,
    required this.samplesWouldApply,
    required this.samplesNotFound,
    required this.samplesAmbiguous,
  });

  @override
  int get hashCode =>
      wouldApply.hashCode ^
      skippedNotFound.hashCode ^
      skippedAmbiguous.hashCode ^
      wouldUpsertOrphanFacetCount.hashCode ^
      samplesWouldApply.hashCode ^
      samplesNotFound.hashCode ^
      samplesAmbiguous.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PreviewImportComicMetadataResultDto &&
          runtimeType == other.runtimeType &&
          wouldApply == other.wouldApply &&
          skippedNotFound == other.skippedNotFound &&
          skippedAmbiguous == other.skippedAmbiguous &&
          wouldUpsertOrphanFacetCount == other.wouldUpsertOrphanFacetCount &&
          samplesWouldApply == other.samplesWouldApply &&
          samplesNotFound == other.samplesNotFound &&
          samplesAmbiguous == other.samplesAmbiguous;
}

class WouldApplySampleDto {
  final String comicId;
  final String path;
  final String title;
  final String matchedComicId;
  final MatchTierDto? matchTier;

  const WouldApplySampleDto({
    required this.comicId,
    required this.path,
    required this.title,
    required this.matchedComicId,
    this.matchTier,
  });

  @override
  int get hashCode =>
      comicId.hashCode ^
      path.hashCode ^
      title.hashCode ^
      matchedComicId.hashCode ^
      matchTier.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WouldApplySampleDto &&
          runtimeType == other.runtimeType &&
          comicId == other.comicId &&
          path == other.path &&
          title == other.title &&
          matchedComicId == other.matchedComicId &&
          matchTier == other.matchTier;
}
