// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'init.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

List<String> listAllPathsFrb() =>
    RustLib.instance.api.crateApiPathListAllPathsFrb();

void addPathFrb({required String rawPath}) =>
    RustLib.instance.api.crateApiPathAddPathFrb(rawPath: rawPath);

void removePathFrb({required String rawPath}) =>
    RustLib.instance.api.crateApiPathRemovePathFrb(rawPath: rawPath);

Stream<List<String>> watchPathsFrb() =>
    RustLib.instance.api.crateApiPathWatchPathsFrb();
