// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'init.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

Future<LibraryProbeResultDto> probeLibraryFrb({
  required String libraryId,
  String? password,
}) => RustLib.instance.api.crateApiProbeProbeLibraryFrb(
  libraryId: libraryId,
  password: password,
);

class LibraryProbeResultDto {
  final String libraryId;
  final int addedCount;
  final int changedCount;
  final int removedCount;
  final bool unreachable;
  final String? errorMessage;
  final PlatformInt64 probedAtMs;
  final bool baselineMissing;

  const LibraryProbeResultDto({
    required this.libraryId,
    required this.addedCount,
    required this.changedCount,
    required this.removedCount,
    required this.unreachable,
    this.errorMessage,
    required this.probedAtMs,
    required this.baselineMissing,
  });

  @override
  int get hashCode =>
      libraryId.hashCode ^
      addedCount.hashCode ^
      changedCount.hashCode ^
      removedCount.hashCode ^
      unreachable.hashCode ^
      errorMessage.hashCode ^
      probedAtMs.hashCode ^
      baselineMissing.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LibraryProbeResultDto &&
          runtimeType == other.runtimeType &&
          libraryId == other.libraryId &&
          addedCount == other.addedCount &&
          changedCount == other.changedCount &&
          removedCount == other.removedCount &&
          unreachable == other.unreachable &&
          errorMessage == other.errorMessage &&
          probedAtMs == other.probedAtMs &&
          baselineMissing == other.baselineMissing;
}
