// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'init.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

void openReaderFrb({
  required String comicId,
  required String path,
  required String resourceType,
}) => RustLib.instance.api.crateApiReaderOpenReaderFrb(
  comicId: comicId,
  path: path,
  resourceType: resourceType,
);

ReaderPageListDto loadPageListFrb({
  required String comicId,
  required String path,
  required String resourceType,
}) => RustLib.instance.api.crateApiReaderLoadPageListFrb(
  comicId: comicId,
  path: path,
  resourceType: resourceType,
);

Uint8List loadPageBytesFrb({
  required String comicId,
  required String path,
  required String resourceType,
  required int pageIndex,
}) => RustLib.instance.api.crateApiReaderLoadPageBytesFrb(
  comicId: comicId,
  path: path,
  resourceType: resourceType,
  pageIndex: pageIndex,
);

void closeReaderFrb({required String comicId}) =>
    RustLib.instance.api.crateApiReaderCloseReaderFrb(comicId: comicId);

void clearReaderSessionsFrb() =>
    RustLib.instance.api.crateApiReaderClearReaderSessionsFrb();

class ReaderPageListDto {
  final String resourceType;
  final int pageCount;
  final List<String> dirPagePaths;

  const ReaderPageListDto({
    required this.resourceType,
    required this.pageCount,
    required this.dirPagePaths,
  });

  @override
  int get hashCode =>
      resourceType.hashCode ^ pageCount.hashCode ^ dirPagePaths.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReaderPageListDto &&
          runtimeType == other.runtimeType &&
          resourceType == other.resourceType &&
          pageCount == other.pageCount &&
          dirPagePaths == other.dirPagePaths;
}
