// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'init.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

InferSeriesResultDto inferSeriesFrb() =>
    RustLib.instance.api.crateApiSeriesInferSeriesFrb();

class InferSeriesResultDto {
  final int groupsApplied;
  final int comicsAssigned;
  final int newSeriesCreated;

  const InferSeriesResultDto({
    required this.groupsApplied,
    required this.comicsAssigned,
    required this.newSeriesCreated,
  });

  @override
  int get hashCode =>
      groupsApplied.hashCode ^
      comicsAssigned.hashCode ^
      newSeriesCreated.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InferSeriesResultDto &&
          runtimeType == other.runtimeType &&
          groupsApplied == other.groupsApplied &&
          comicsAssigned == other.comicsAssigned &&
          newSeriesCreated == other.newSeriesCreated;
}
