// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'comic.dart';
import 'init.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`

Stream<List<SeriesDto>> watchAllSeriesFrb() =>
    RustLib.instance.api.crateApiSeriesWatchAllSeriesFrb();

List<SeriesDto> getAllSeriesFrb() =>
    RustLib.instance.api.crateApiSeriesGetAllSeriesFrb();

PagedSeriesResultDto fetchSeriesPageFrb({
  required PageRequestDto request,
  required SeriesFilterDto filter,
  required SeriesSortOptionDto sort,
}) => RustLib.instance.api.crateApiSeriesFetchSeriesPageFrb(
  request: request,
  filter: filter,
  sort: sort,
);

SeriesDto? findSeriesByIdFrb({required String seriesId}) =>
    RustLib.instance.api.crateApiSeriesFindSeriesByIdFrb(seriesId: seriesId);

void updateSeriesUserMetaFrb({
  required String seriesId,
  required UpdateSeriesUserMetaFrbDto meta,
}) => RustLib.instance.api.crateApiSeriesUpdateSeriesUserMetaFrb(
  seriesId: seriesId,
  meta: meta,
);

void setSeriesItemsOrderFrb({
  required String seriesId,
  required List<String> orderedComicIds,
}) => RustLib.instance.api.crateApiSeriesSetSeriesItemsOrderFrb(
  seriesId: seriesId,
  orderedComicIds: orderedComicIds,
);

List<SeriesDto> searchSeriesByKeywordFrb({required String keyword}) => RustLib
    .instance
    .api
    .crateApiSeriesSearchSeriesByKeywordFrb(keyword: keyword);

List<SeriesDto> searchSeriesByTagExpressionFrb({
  required List<String> mustInclude,
  required List<String> optionalOr,
  required List<String> mustExclude,
}) => RustLib.instance.api.crateApiSeriesSearchSeriesByTagExpressionFrb(
  mustInclude: mustInclude,
  optionalOr: optionalOr,
  mustExclude: mustExclude,
);

List<SeriesComicOrderEntryDto> loadHomeSeriesComicOrderMapFrb() =>
    RustLib.instance.api.crateApiSeriesLoadHomeSeriesComicOrderMapFrb();

Stream<List<SeriesComicOrderEntryDto>> watchHomeSeriesComicOrderMapFrb() =>
    RustLib.instance.api.crateApiSeriesWatchHomeSeriesComicOrderMapFrb();

class PagedSeriesResultDto {
  final List<SeriesDto> items;
  final PlatformInt64 totalCount;
  final int page;
  final int pageSize;

  const PagedSeriesResultDto({
    required this.items,
    required this.totalCount,
    required this.page,
    required this.pageSize,
  });

  @override
  int get hashCode =>
      items.hashCode ^ totalCount.hashCode ^ page.hashCode ^ pageSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PagedSeriesResultDto &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          totalCount == other.totalCount &&
          page == other.page &&
          pageSize == other.pageSize;
}

class SeriesComicOrderEntryDto {
  final String key;
  final int sortOrder;

  const SeriesComicOrderEntryDto({required this.key, required this.sortOrder});

  @override
  int get hashCode => key.hashCode ^ sortOrder.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SeriesComicOrderEntryDto &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          sortOrder == other.sortOrder;
}

class SeriesDto {
  final String seriesId;
  final String folderPath;
  final String name;
  final String serializationStatus;
  final int? totalCount;
  final List<SeriesItemDto> items;

  const SeriesDto({
    required this.seriesId,
    required this.folderPath,
    required this.name,
    required this.serializationStatus,
    this.totalCount,
    required this.items,
  });

  @override
  int get hashCode =>
      seriesId.hashCode ^
      folderPath.hashCode ^
      name.hashCode ^
      serializationStatus.hashCode ^
      totalCount.hashCode ^
      items.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SeriesDto &&
          runtimeType == other.runtimeType &&
          seriesId == other.seriesId &&
          folderPath == other.folderPath &&
          name == other.name &&
          serializationStatus == other.serializationStatus &&
          totalCount == other.totalCount &&
          items == other.items;
}

class SeriesFilterDto {
  final bool showR18;
  final bool r18Only;
  final String? query;
  final bool requireItems;

  const SeriesFilterDto({
    required this.showR18,
    required this.r18Only,
    this.query,
    required this.requireItems,
  });

  @override
  int get hashCode =>
      showR18.hashCode ^
      r18Only.hashCode ^
      query.hashCode ^
      requireItems.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SeriesFilterDto &&
          runtimeType == other.runtimeType &&
          showR18 == other.showR18 &&
          r18Only == other.r18Only &&
          query == other.query &&
          requireItems == other.requireItems;
}

class SeriesItemDto {
  final String seriesId;
  final String comicId;
  final int sortOrder;

  const SeriesItemDto({
    required this.seriesId,
    required this.comicId,
    required this.sortOrder,
  });

  @override
  int get hashCode => seriesId.hashCode ^ comicId.hashCode ^ sortOrder.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SeriesItemDto &&
          runtimeType == other.runtimeType &&
          seriesId == other.seriesId &&
          comicId == other.comicId &&
          sortOrder == other.sortOrder;
}

class SeriesSortOptionDto {
  final bool descending;

  const SeriesSortOptionDto({required this.descending});

  @override
  int get hashCode => descending.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SeriesSortOptionDto &&
          runtimeType == other.runtimeType &&
          descending == other.descending;
}

class UpdateSeriesUserMetaFrbDto {
  final String? name;
  final String? serializationStatus;
  final int? totalCount;
  final bool clearTotalCount;

  const UpdateSeriesUserMetaFrbDto({
    this.name,
    this.serializationStatus,
    this.totalCount,
    required this.clearTotalCount,
  });

  static Future<UpdateSeriesUserMetaFrbDto> default_() =>
      RustLib.instance.api.crateApiSeriesUpdateSeriesUserMetaFrbDtoDefault();

  @override
  int get hashCode =>
      name.hashCode ^
      serializationStatus.hashCode ^
      totalCount.hashCode ^
      clearTotalCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateSeriesUserMetaFrbDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          serializationStatus == other.serializationStatus &&
          totalCount == other.totalCount &&
          clearTotalCount == other.clearTotalCount;
}
