// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'init.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they have generic arguments: `emit_or_closed`

/// 将 watch 循环结果中的「流已关闭」规范为成功退出。
Future<void> normalizeWatchResult({required ResultHentaiError result}) =>
    RustLib.instance.api.crateApiStreamWatchNormalizeWatchResult(
      result: result,
    );

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Result < () , HentaiError >>>
abstract class ResultHentaiError implements RustOpaqueInterface {}
