// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'init.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `map_phase`, `map_progress`, `map_route`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`

SyncHandleDto createSyncHandleFrb() =>
    RustLib.instance.api.crateApiSyncCreateSyncHandleFrb();

void cancelSyncFrb({required SyncHandleDto handle}) =>
    RustLib.instance.api.crateApiSyncCancelSyncFrb(handle: handle);

Stream<SyncLibraryProgressDto> syncLibraryFrb({
  required SyncHandleDto handle,
}) => RustLib.instance.api.crateApiSyncSyncLibraryFrb(handle: handle);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SyncHandleDto>>
abstract class SyncHandleDto implements RustOpaqueInterface {}

class LibrarySyncCountsDto {
  final int dir;
  final int zip;
  final int cbz;
  final int epub;

  const LibrarySyncCountsDto({
    required this.dir,
    required this.zip,
    required this.cbz,
    required this.epub,
  });

  @override
  int get hashCode =>
      dir.hashCode ^ zip.hashCode ^ cbz.hashCode ^ epub.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LibrarySyncCountsDto &&
          runtimeType == other.runtimeType &&
          dir == other.dir &&
          zip == other.zip &&
          cbz == other.cbz &&
          epub == other.epub;
}

enum SyncLibraryPhaseDto {
  clearingLibrary,
  scanning,
  writingDb,
  generatingThumbnails,
  done,
}

class SyncLibraryProgressDto {
  final SyncLibraryPhaseDto phase;
  final SyncLibraryRouteDto route;
  final String? currentPath;
  final int acceptedTotal;
  final LibrarySyncCountsDto counts;
  final int? removedCount;
  final int? addedCount;
  final int? keptCount;
  final int? thumbnailTotal;
  final int? thumbnailDone;
  final int? thumbnailFailedCount;

  const SyncLibraryProgressDto({
    required this.phase,
    required this.route,
    this.currentPath,
    required this.acceptedTotal,
    required this.counts,
    this.removedCount,
    this.addedCount,
    this.keptCount,
    this.thumbnailTotal,
    this.thumbnailDone,
    this.thumbnailFailedCount,
  });

  @override
  int get hashCode =>
      phase.hashCode ^
      route.hashCode ^
      currentPath.hashCode ^
      acceptedTotal.hashCode ^
      counts.hashCode ^
      removedCount.hashCode ^
      addedCount.hashCode ^
      keptCount.hashCode ^
      thumbnailTotal.hashCode ^
      thumbnailDone.hashCode ^
      thumbnailFailedCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncLibraryProgressDto &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          route == other.route &&
          currentPath == other.currentPath &&
          acceptedTotal == other.acceptedTotal &&
          counts == other.counts &&
          removedCount == other.removedCount &&
          addedCount == other.addedCount &&
          keptCount == other.keptCount &&
          thumbnailTotal == other.thumbnailTotal &&
          thumbnailDone == other.thumbnailDone &&
          thumbnailFailedCount == other.thumbnailFailedCount;
}

enum SyncLibraryRouteDto { noRootsNoop, noRootsCleared, withRoots }
